Repository BetterSocial/mobileapp, pull requests merged in 2023-12, with the labels that each got.

#1709 Merge/viewposttime in topic feeds
  ios/Podfile.lock
  src/screens/FeedScreen/hooks/useCoreFeed.js
  src/screens/FeedScreen/hooks/useViewPostTimeHook.ts
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#1706 fix: rename internal accounts
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  src/components/DevDummyLogin/index.js
Labels: merge to main, on testing

#1710 Merge/ping 3206 image picker
  android/app/build.gradle
  android/app/src/main/java/org/bettersocial/MainApplication.java
  android/settings.gradle
  ios/Podfile.lock
  package.json
  src/screens/InputUsername/index.js
  yarn.lock
Labels: need review, merge to staging

#1716 Merge/ping 776
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/screens/FeedScreen/hooks/useCoreFeed.js
  src/screens/FeedScreen/hooks/useFeedPreloadHook.ts
  src/screens/FeedScreen/hooks/useFeedUtilsHook.ts
  src/screens/FeedScreen/hooks/useViewPostTimeHook.ts
  src/screens/FeedScreen/index.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/ProfileTiktokScroll.js
  src/screens/ProfileScreen/index.js
  src/screens/TopicPageScreen/index.js
  src/utils/constants/index.js
Labels: need review, waiting for visual feedback, merge to staging

#1714 feat: ping 3066 chat v21
  __mocks__/react-native-gesture-handler.ts
  __mocks__/react-native-reanimated.ts
  __tests__/components/AnonymousChat/child/ChatItemMyTextV2.test.tsx
  __tests__/components/AnonymousChat/child/ChatItemTargetText.test.tsx
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  __tests__/database/migration/index.test.ts
  jestSetup.js
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/AnonymousChat/child/ChatItemText.style.ts
  src/components/AnonymousChat/child/ChatReplyPreview.tsx
  src/components/AnonymousChat/child/ChatReplyView.tsx
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/database/migration/file/migration_version_7.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/ChatSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/constant/index.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/core/websocket/types.d.ts
  src/hooks/screen/useChatScreenHook.ts
  src/hooks/screen/useMessageHook.ts
  src/screens/ChannelListScreenV2/index.tsx
  src/screens/WebsocketResearchScreen/SampleChatScreen.tsx
  src/screens/WebsocketResearchScreen/SignedChatScreen.tsx
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  src/utils/constants/index.js
  types/component/AnonymousChat/ChatReplyView.types.ts
  types/hooks/screens/useChatScreenHook.types.ts
  types/hooks/screens/useMessageHook.types.ts
Labels: need review, merge to staging

#1718 feat: ping 3148 karma score staging
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowUserInfo.test.js.snap
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/assets/Logogram.png
  src/components/Karma/CircleGradient.tsx
  src/components/Karma/utils.ts
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/FollowInfoRow.js
  src/screens/ProfileScreen/elements/KarmaScore.tsx
  src/screens/ProfileScreen/elements/ProfilePicture.js
  src/screens/ProfileScreen/index.js
  src/screens/WhotoFollow/elements/ItemUser.js
  src/screens/WhotoFollow/elements/UserInfo.js
  src/screens/WhotoFollow/index.js
Labels: need review, merge to staging

#1721 Merge/ping 3144
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  __tests__/hooks/useProfileScreenHook.test.js
  src/components/DevDummyLogin/index.js
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/hooks/screen/useProfileScreenHook.js
  src/screens/FeedScreen/hooks/useCoreFeed.js
  src/screens/FeedScreen/hooks/useMappingColorHook.ts
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/index.js
  src/screens/TopicPageScreen/index.js
  src/utils/Utils.js
  src/utils/storage/custom/feedStorage.ts
  src/utils/storage/custom/tokenStorage.ts
  src/utils/storage/index.ts
Labels: waiting for visual feedback, merge to staging

#1711 fix: image picker not working on android
  android/app/build.gradle
  android/app/src/main/java/org/bettersocial/MainApplication.java
  android/settings.gradle
  ios/Podfile.lock
  package.json
  src/screens/InputUsername/index.js
  yarn.lock
Labels: merge to main, on testing

#1735 fix: karma ripples dot
  src/components/Karma/CircleGradient.tsx
Labels: need review, merge to staging

#1708 Feat/viewposttime in topic feeds
  ios/Podfile.lock
  src/screens/FeedScreen/hooks/useCoreFeed.js
  src/screens/FeedScreen/hooks/useViewPostTimeHook.ts
  src/screens/TopicPageScreen/index.js
Labels: merge to main, on testing

#1673 (Main) PING 3380 fix text search in news screen
  src/components/TopicsChip/TopicsChip.js
  src/screens/NewsScreen/Search.js
  src/utils/string/StringConstant/index.js
Labels: merge to main, on testing

#1692 (Main) PING 3364 add transparent color in the topic chip
  src/components/TopicsChip/TopicsChip.js
  src/utils/colors/index.js
Labels: merge to main, on testing

#1682 (MAIN) PING-3152 remove see more on other profile
  src/screens/OtherProfile/elements/BioAndChat.js
Labels: merge to main, on testing

#1745 feat: 2551 send media interaction
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  __tests__/database/migration/file/index.test.ts
  __tests__/database/migration/index.test.ts
  __tests__/database/schema/ChatSchema.test.ts
  ios/BetterSocialStaging/Info.plist
  package.json
  src/assets/icon/IconAdd.js
  src/assets/icon/IconFile.js
  src/assets/icon/IconPlusAttachment.js
  src/assets/icon/IconVideoPlay.js
  src/assets/icons/images/file.svg
  src/assets/icons/images/gif.svg
  src/assets/icons/images/medias.svg
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemText.style.ts
  src/components/AnonymousChat/child/ChatReplyPreview.tsx
  src/components/BottomSheet/BottomSheet.js
  src/components/Chat/BottomSheetAttachment.js
  src/components/Chat/BottomSheetGif.js
  src/components/Chat/InputMessageV2.tsx
  src/database/migration/file/index.ts
  src/database/migration/file/migration_version_8.ts
  src/database/migration/index.ts
  src/database/schema/ChatSchema.ts
  src/hooks/screen/useChatScreenHook.ts
  src/hooks/screen/useMessageHook.ts
  src/navigations/root-stack.js
  src/screens/ImageViewer/index.js
  src/screens/VideoViewer/index.js
  src/service/gif.js
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  src/utils/image/index.ts
  src/utils/string/StringUtils.js
  types/component/AnonymousChat/BaseChatItem.types.ts
  types/hooks/screens/useChatScreenHook.types.ts
  types/hooks/screens/useMessageHook.types.ts
Labels: merge to staging

#1752 fix: feedback ping 2551 send media staging
  src/components/Chat/BottomSheetGif.js
  src/components/Chat/InputMessageV2.tsx
  src/screens/ImageViewer/index.js
  src/service/gif.js
  src/utils/permission/index.js
Labels: merge to staging

#1757 PING 3072 update utils/theme color
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  __tests__/screens/GroupInfo/__snapshots__/GroupInfo.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  src/utils/theme/index.js
Labels: need review, merge to main

#1758 Feat/ping 3142
  __tests__/hooks/useGroupSetting.test.js
  __tests__/screens/ChannelListScreenV2/ChannelListScreenV2.test.js
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/GroupInfo/GroupInfo.test.js
  __tests__/screens/GroupInfo/__snapshots__/GroupInfo.test.js.snap
  __tests__/screens/GroupSetting/EditGroup.test.js
  __tests__/screens/GroupSetting/GroupSetting.test.js
  __tests__/screens/GroupSetting/__snapshots__/EditGroup.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  __tests__/screens/WebView/TermsAndCondition.test.js
  __tests__/screens/WebView/__snapshots__/TermsAndCondition.test.js.snap
  ios/Podfile.lock
  src/components/Chat/ActionChat.js
  src/components/Chat/AnonymousInputMessage.tsx
  src/components/Chat/CostomListMessage.js
  src/components/Chat/Header.js
  src/components/Chat/InputMessage.js
  src/components/Chat/MessageText.js
  src/components/Chat/MessageWithImage.js
  src/components/Chat/MessageWithLink.js
  src/components/Chat/ModalImageSingleDetail.js
  src/components/Chat/ProfileMessage.js
  src/components/Chat/ReplyMessageText.js
  src/components/Chat/SheetEmoji.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/navigations/HomeBottomTabs.js
  src/navigations/root-stack.js
  src/screens/AnonymousChannelListScreen/index.tsx
  src/screens/AnonymousChatScreen/index.tsx
  src/screens/ChannelListScreen/elements/CustomPreviewAvatar.js
  src/screens/ChannelListScreen/elements/CustomPreviewMessage.js
  src/screens/ChannelListScreen/elements/CustomPreviewUnreadCount.js
  src/screens/ChannelListScreen/elements/components/AvatarPostNotif.js
  src/screens/ChannelListScreen/elements/components/PostNotificationPreview.js
  src/screens/ChannelScreen/index.js
  src/screens/ChatDetailPage/elements/CustomMessageAvatar.js
  src/screens/ChatDetailPage/elements/ImageSendPreview.js
  src/screens/ChatDetailPage/index.js
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/DetailGroupImage/index.js
  src/screens/GroupInfo/GroupMedia.js
  src/screens/GroupInfo/index.js
  src/screens/GroupSetting/elements/EditGroup.js
  src/screens/GroupSetting/hooks/useGroupSetting.js
  src/screens/GroupSetting/index.js
  src/screens/Settings/index.js
  src/screens/SignedChatScreen/index.tsx
  src/screens/WebView/TermsAndCondition.js
  src/screens/WebsocketResearchScreen/index.tsx
  src/screens/index.js
Labels: need review

#1759 Merge/ping 3142
  __tests__/hooks/useGroupSetting.test.js
  __tests__/screens/ChannelListScreenV2/ChannelListScreenV2.test.js
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/GroupInfo/GroupInfo.test.js
  __tests__/screens/GroupInfo/__snapshots__/GroupInfo.test.js.snap
  __tests__/screens/GroupSetting/EditGroup.test.js
  __tests__/screens/GroupSetting/GroupSetting.test.js
  __tests__/screens/GroupSetting/__snapshots__/EditGroup.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  __tests__/screens/WebView/TermsAndCondition.test.js
  __tests__/screens/WebView/__snapshots__/TermsAndCondition.test.js.snap
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/components/Chat/ActionChat.js
  src/components/Chat/CostomListMessage.js
  src/components/Chat/Header.js
  src/components/Chat/InputMessage.js
  src/components/Chat/MessageText.js
  src/components/Chat/MessageWithImage.js
  src/components/Chat/MessageWithLink.js
  src/components/Chat/ModalImageSingleDetail.js
  src/components/Chat/ProfileMessage.js
  src/components/Chat/ReplyMessageText.js
  src/components/Chat/SheetEmoji.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/navigations/HomeBottomTabs.js
  src/navigations/root-stack.js
  src/screens/AnonymousChannelListScreen/index.tsx
  src/screens/AnonymousChatScreen/index.tsx
  src/screens/ChannelListScreen/elements/CustomPreviewAvatar.js
  src/screens/ChannelListScreen/elements/CustomPreviewMessage.js
  src/screens/ChannelListScreen/elements/CustomPreviewUnreadCount.js
  src/screens/ChannelListScreen/elements/components/AvatarPostNotif.js
  src/screens/ChannelListScreen/elements/components/PostNotificationPreview.js
  src/screens/ChannelScreen/index.js
  src/screens/ChatDetailPage/elements/CustomMessageAvatar.js
  src/screens/ChatDetailPage/elements/ImageSendPreview.js
  src/screens/ChatDetailPage/index.js
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/DetailGroupImage/index.js
  src/screens/GroupInfo/GroupMedia.js
  src/screens/GroupInfo/index.js
  src/screens/GroupSetting/elements/EditGroup.js
  src/screens/GroupSetting/hooks/useGroupSetting.js
  src/screens/GroupSetting/index.js
  src/screens/Settings/index.js
  src/screens/SignedChatScreen/index.tsx
  src/screens/WebView/TermsAndCondition.js
  src/screens/WebsocketResearchScreen/index.tsx
  src/screens/index.js
  yarn.lock
Labels: need review, merge to staging

#1765 Merge/ping 3136
  App.js
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/BetterSocialStaging/Info.plist
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/hooks/screen/useChatInfoHook.ts
  src/screens/AnonymousChatScreen/index.tsx
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/GroupInfo/elements/ModalAction.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/utils/theme/index.js
  types/hooks/screens/useAnonymousChatInfoScreenHook.types.ts
Labels: need review, merge to staging

#1766 fix: add loader indicator when creating new chat from chat detail
  App.js
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap
  __tests__/screens/GroupInfo/GroupInfo.test.js
  __tests__/screens/GroupInfo/__snapshots__/GroupInfo.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/BetterSocialStaging/Info.plist
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/hooks/screen/useChatInfoHook.ts
  src/screens/GroupInfo/elements/ModalAction.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/WebsocketResearchScreen/SampleChatInfoScreen.tsx
  types/hooks/screens/useAnonymousChatInfoScreenHook.types.ts
Labels: need review, merge to main, on testing

#1764 Fix/feedback ping 2551 send media staging
  src/components/BottomSheet/BottomSheet.js
  src/components/Chat/InputMessageV2.tsx
  src/hooks/screen/useChatScreenHook.ts
Labels: need review, waiting for visual feedback, merge to staging

#1717 feat: ping 3148 karma score
  __mocks__/react-native-svg.tsx
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowUserInfo.test.js.snap
  src/assets/BetterSocialLogoGram.js
  src/assets/Logogram.png
  src/assets/index.js
  src/components/Karma/CircleGradient.tsx
  src/components/Karma/GradientCircularProgress.tsx
  src/components/Karma/utils.ts
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/FollowInfoRow.js
  src/screens/ProfileScreen/elements/KarmaScore.tsx
  src/screens/ProfileScreen/elements/ProfilePicture.js
  src/screens/ProfileScreen/index.js
  src/screens/WhotoFollow/elements/ItemUser.js
  src/screens/WhotoFollow/elements/UserInfo.js
  src/screens/WhotoFollow/index.js
  src/utils/theme/index.js
Labels: need review, merge to main, on testing
