Repository BetterSocial/mobileapp, pull requests merged in 2024-06, with the labels that each got.

#2362 fix: add force search when press search button on keyboard
  src/screens/DiscoveryScreenV2/elements/Search.js
Labels: need review, merge to main, on testing

#2350 fix: change news date
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/Card/Card.js
  src/components/Card/CardHeader.js
  src/screens/FeedScreen/ContentLink.js
Labels: need review, merge to main, on testing

#2370 feat: change privacy page and help center page to external browser
  src/screens/Settings/index.js
  src/utils/constants/index.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2374 fix: loading and retry failed create post PING-4043
  src/screens/CreatePost/index.js
  src/utils/string/StringConstant/index.js
Labels: need review, merge to staging

#2379 Create community v3
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/chat/useMoveChatTypeHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/screens/ContactScreen/elements/Search.js
  src/screens/ContactScreen/index.js
  src/screens/CreateCommunity/index.js
  src/screens/CreatePost/index.js
  src/screens/TopicPageScreen/index.js
  src/service/repo/signedMessageRepo.ts
  src/service/topics.ts
  src/utils/string/StringUtils.js
Labels: need review, merge to staging

#2380 [PING-3769] feat: show anon topic chat tab
  src/components/ChatList/CommunityChannelItem.tsx
  src/components/ChatList/elements/ChannelImage.style.ts
  src/components/ChatList/elements/ChannelImage.tsx
  src/database/schema/ChannelListSchema.ts
  src/hooks/screen/useAnonymousChannelListHook.ts
  src/hooks/screen/useRootChannelListHook.ts
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/TopicPageScreen/elements/BottomSheetFollow.tsx
  types/component/ChatList/ChannelImage.types.ts
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
Labels: need review, merge to staging

#2366 fix: PING-4095 adjust some analytics events on onboarding
  src/libraries/analytics/analyticsEventTracking.ts
  src/screens/InputUsername/index.js
  src/screens/LocalCommunity/index.js
  src/screens/Topics/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2369 feat: change privacy page and help center page to external browser
  src/screens/Settings/index.js
  src/utils/constants/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2392 fix: unable to delete post on profile screen
  src/screens/FeedScreen/Header.js
  src/screens/ProfileScreen/index.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2390 Feat/ping 3180
  __tests__/components/AnonymousChat/child/ChatItemMyTextV2.test.tsx
  __tests__/components/AnonymousChat/child/ChatItemTargetText.test.tsx
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  ios/Podfile.lock
  package.json
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/ContextMenuView/ChatContextMenuView.tsx
  src/database/schema/ChatSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/chat/useMessageHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/core/websocket/types.d.ts
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  src/utils/share/index.js
  types/component/AnonymousChat/BaseChatItem.types.ts
  yarn.lock
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2388 feat: enable longpress copy on chat
  __tests__/components/AnonymousChat/child/ChatItemMyTextV2.test.tsx
  __tests__/components/AnonymousChat/child/ChatItemTargetText.test.tsx
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  ios/Podfile.lock
  package.json
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/ContextMenuView/ChatContextMenuView.tsx
  src/utils/share/index.js
  yarn.lock
Labels: need review, merge to staging, on testing

#2389 Feat/ping 3180
  __tests__/components/AnonymousChat/child/ChatItemMyTextV2.test.tsx
  __tests__/components/AnonymousChat/child/ChatItemTargetText.test.tsx
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  ios/Podfile.lock
  package.json
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/ContextMenuView/ChatContextMenuView.tsx
  src/database/schema/ChatSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/chat/useMessageHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/core/websocket/types.d.ts
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  src/utils/share/index.js
  types/component/AnonymousChat/BaseChatItem.types.ts
  yarn.lock
Labels: need review, merge to main, waiting for visual feedback, on testing

#2387 feat: enable longpress copy on chat
  __tests__/components/AnonymousChat/child/ChatItemMyTextV2.test.tsx
  __tests__/components/AnonymousChat/child/ChatItemTargetText.test.tsx
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  ios/Podfile.lock
  package.json
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/ContextMenuView/ChatContextMenuView.tsx
  src/utils/share/index.js
  yarn.lock
Labels: need review, merge to main, on testing

#2391 fix: unable to delete post on profile screen
  src/screens/FeedScreen/Header.js
  src/screens/ProfileScreen/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2397 fix: link detection on my chat item and target chat item
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/Text/LinkDetectionText.tsx
  src/screens/OtherProfile/elements/BioAndChat.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2403 [PING-4154] fix: show profile on topic member
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/UserFragmentCommunity.js
  src/screens/TopicMemberScreen/index.js
Labels: need review, merge to staging

#2402 Merge/fix/ping 4142 new
  src/screens/DiscoveryScreenV2/fragment/UserFragmentCommunity.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/DiscoveryScreenV2/hooks/useDiscovery.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/screens/OtherProfile/index.js
  src/service/topics.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2401 Fix/ping 4142 new
  src/screens/DiscoveryScreenV2/fragment/UserFragmentCommunity.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/DiscoveryScreenV2/hooks/useDiscovery.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/screens/OtherProfile/index.js
  src/service/topics.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2413 [PING-4120] fix: community icon on chat tab
  src/components/ChatList/CommunityChannelItem.tsx
  src/components/ChatList/elements/ChannelImage.style.ts
  src/components/ChatList/elements/ChannelImage.tsx
  src/hooks/screen/useAnonymousChannelListHook.ts
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  types/component/ChatList/ChannelImage.types.ts
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
Labels: need review, merge to main

#2407 Fix/ping 4136
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/service/topics.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2418 fix: remove attachment json if message_type is reply prompt
  src/database/schema/ChatSchema.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2416 fix: old chat cache still exists even after unmount
  src/hooks/screen/services/chatScreenHooks.js
  src/hooks/screen/useChatScreenHook.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2415 fix: add hasUserPosted on onesignal subscribtion
  __tests__/service/onesignal/OneSignalUtil.test.ts
  src/service/onesignal/index.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2404 [PING-4154] feat: show profile on topic member list
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/UserFragmentCommunity.js
  src/screens/TopicMemberScreen/index.js
Labels: need review, merge to main

#2423 fix: crash when start posting from other profile
  src/screens/CreatePost/index.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2421 Fix/ping 4148 reply prompt
  __tests__/database/schema/ChatSchema.test.ts
  src/database/schema/ChatSchema.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2408 fix: clear chats data when screen is unmounted
  src/core/queue/DatabaseQueue.ts
  src/database/schema/ChatSchema.ts
  src/hooks/core/chat/useChannelGetInitialMessagesHook.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/services/chatScreenHooks.js
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChannelListScreen/index.tsx
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/service/repo/signedMessageRepo.ts
  src/utils/constants/index.js
  types/component/AnonymousChat/MessageChannelItem.types.ts
  types/component/ChatList/ChannelItem.types.ts
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2422 fix: crash when start posting from other profile
  src/screens/CreatePost/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2414 fix: add hasUserPosted on onesignal subscribtion
  __tests__/service/onesignal/OneSignalUtil.test.ts
  src/service/onesignal/index.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2420 [PING-4157] fix: glitch community member list
  src/navigations/root-stack.js
  src/screens/TopicMemberScreen/index.js
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main

#2433 [PING-4153] fix: shimmer on topic page member count
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#2432 [PING-4165] fix: rollback show own profile in topic member list
  src/screens/TopicMemberScreen/index.js
Labels: need review, merge to staging

#2438 Fix/ping 4148 reply prompt
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/navigations/root-stack.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2417 fix: remove attachment json if message_type is reply prompt
  __tests__/database/schema/ChatSchema.test.ts
  src/database/schema/ChatSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/navigations/root-stack.js
Labels: need review, merge to main, waiting for visual feedback, on testing
