Repository BetterSocial/mobileapp, pull requests merged in 2024-04, with the labels that each got.

#2166 Feat/ping 3842 Empty Anon Chat tab staging
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Contents.json
  src/assets/icons/Ic_arrow_right.js
  src/assets/images/empty_incognito.png
  src/components/WarningAnimateMessage/index.js
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ChannelListScreenV2/IncognitoEmptyChat/index.tsx
  src/screens/CreatePost/index.js
  src/utils/storage/index.ts
Labels: need review, merge to staging

#2172 fix: ping-3876 crash start posting
  src/screens/CreatePost/index.js
Labels: need review, merge to main

#2150 Feat/ping 3360 who to follow v2 main
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowLabel.test.js.snap
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowUserInfo.test.js.snap
  src/assets/icon/IconAdd.js
  src/assets/icon/IconCheck.js
  src/screens/WhotoFollow/elements/ItemUser.js
  src/screens/WhotoFollow/elements/Label.js
  src/screens/WhotoFollow/elements/UserInfo.js
  src/screens/WhotoFollow/index.js
  src/service/topics.js
Labels: need review, merge to main

#2164 Feat/ping 3842 Empty Anon Chat tab main
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Contents.json
  src/assets/icons/Ic_arrow_right.js
  src/assets/images/empty_incognito.png
  src/components/WarningAnimateMessage/index.js
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ChannelListScreenV2/IncognitoEmptyChat/index.tsx
  src/screens/CreatePost/index.js
  src/utils/storage/index.ts
Labels: need review, merge to main

#2174 feat: ping-3865 onboarding screens
  src/assets/background/bg_onboarding_top.png
  src/assets/background/fg_onboarding_full_1.png
  src/assets/background/fg_onboarding_full_2.png
  src/assets/background/fg_onboarding_full_3.png
  src/assets/background/fg_onboarding_full_4.png
  src/screens/SignInV2/elements/SlideShow.js
Labels: merge to main

#2175 feat: ping-3865 onboarding screens
  src/assets/background/bg_onboarding_top.png
  src/assets/background/fg_onboarding_full_1.png
  src/assets/background/fg_onboarding_full_2.png
  src/assets/background/fg_onboarding_full_3.png
  src/assets/background/fg_onboarding_full_4.png
  src/screens/SignInV2/elements/SlideShow.js
Labels: need review, merge to staging

#2180 fix: conflict code staging
  __tests__/components/AnonymousChat/__snapshots__/AnonymousChatHeader.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelAnonymousSubImage.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelPostNotificationMessage.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelTitle.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  __tests__/components/Blocking/__snapshots__/SpecificIssue.test.js.snap
  __tests__/components/Button/__snapshots__/ButtonAddTopicPost.test.js.snap
  __tests__/components/Comments/WriteComment.test.js
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowLabel.test.js.snap
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowUserInfo.test.js.snap
  __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  __tests__/screens/FeedScreen/__snapshots__/ContentPoll.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  src/components/ReplyComment/index.js
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
Labels: need review, merge to staging

#2182 Feat/splashscreen android ios ping 3862 ping 3863
  android/app/src/main/res/drawable-hdpi/helio.png
  android/app/src/main/res/drawable-ldpi/helio.png
  android/app/src/main/res/drawable-xhdpi/helio.png
  android/app/src/main/res/drawable-xxhdpi/helio.png
  android/app/src/main/res/drawable-xxxhdpi/helio.png
  android/app/src/main/res/drawable/helio.png
  android/app/src/main/res/values/colors.xml
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_1x.png
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_2x.png
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_3x.png
  ios/BetterSocial/LaunchScreen.storyboard
Labels: need review, merge to staging

#2186 fix: ping 3898 loading when add participant
  src/screens/ContactScreen/index.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
Labels: need review, merge to staging

#2184 Fix/dynamic link
  __tests__/utils/share.test.js
  ios/BetterSocial/BetterSocial.entitlements
  ios/BetterSocial/BetterSocialRelease.entitlements
  ios/BetterSocialDevRelease.entitlements
  ios/BetterSocialStaging/BetterSocialStagingRelease.entitlements
  ios/Development/GoogleService-Info.plist
  ios/Helio.xcodeproj/project.pbxproj
  src/configs/FirebaseConfig.js
  src/screens/OtherProfile/index.js
  src/utils/share/index.js
Labels: need review, merge to staging, on testing

#2192 [PING-3822] feat: feed redesign
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelTitle.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  __tests__/components/Blocking/__snapshots__/SpecificIssue.test.js.snap
  __tests__/components/PreviewComment/PreviewComment.test.js
  __tests__/components/TopicText/__snapshots__/index.test.js.snap
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowLabel.test.js.snap
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowUserInfo.test.js.snap
  __tests__/hooks/useFeed.test.js
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/assets/arrow/Ic_downvote_off.js
  src/assets/arrow/Ic_downvote_on.js
  src/assets/arrow/Ic_upvote_off.js
  src/assets/arrow/Ic_upvote_on.js
  src/assets/icon/ElipsisIcon.js
  src/assets/icon/IconCommentArrow.tsx
  src/assets/timer/EightyEight_hundred.js
  src/assets/timer/Fivety_sixtyTwo.js
  src/assets/timer/SeventyFive_eightySeven.js
  src/assets/timer/SixtyThree_seventyFour.js
  src/assets/timer/ThirtySeven_fourtyNine.js
  src/assets/timer/TwentyFive_thirtySix.js
  src/components/AnonymousAvatar/index.js
  src/components/AnonymousUsername/index.js
  src/components/Button/Button.js
  src/components/Card/Card.js
  src/components/Chat/BottomSheetGif.js
  src/components/CommentUsername/CommentUsername.js
  src/components/Comments/Comment.js
  src/components/Comments/ReplyCommentItem.js
  src/components/Footer/Footer.js
  src/components/Header/HeaderContact.js
  src/components/PreviewComment/index.js
  src/components/ReadMore/index.js
  src/components/SendIcon/index.tsx
  src/components/TopicText/index.js
  src/components/TopicsChip/TopicsChip.js
  src/navigations/HomeBottomTabs.js
  src/screens/ChannelListScreen/elements/Search.js
  src/screens/ContactScreen/elements/Search.js
  src/screens/DiscoveryScreenV2/elements/Search.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentLink.js
  src/screens/FeedScreen/Header.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/elements/AddCommentPreview.tsx
  src/screens/FeedScreen/elements/BlurredLayer.js
  src/screens/FeedScreen/elements/Search.js
  src/screens/FeedScreen/hooks/useFeed.js
  src/screens/FeedScreen/index.js
  src/screens/GroupInfo/elements/ModalAction.js
  src/screens/NewsScreen/Search.js
  src/screens/ProfileScreen/elements/AnonymousTab.js
  src/screens/Settings/element/ProfileSettingItem.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/index.js
  src/utils/dimen/index.js
  src/utils/theme/index.js
Labels: need review, merge to staging

#2189 feat: ping-3895 background message handler
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/service/repo/messageRepo.ts
Labels: need review

#2204 feat: ping-3895 background message handler
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/service/repo/messageRepo.ts
Labels: need review, merge to main

#2183 Fix/dynamic link
  __tests__/utils/share.test.js
  ios/BetterSocial/BetterSocial.entitlements
  ios/BetterSocial/BetterSocialRelease.entitlements
  ios/BetterSocialDevRelease.entitlements
  ios/BetterSocialStaging/BetterSocialStagingRelease.entitlements
  ios/Helio.xcodeproj/project.pbxproj
  src/configs/FirebaseConfig.js
  src/navigations/HomeBottomTabs.js
  src/navigations/root-stack.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
  src/utils/share/index.js
Labels: need review, merge to main, on testing

#2208 fix: ping-3926 message double/redundant on anon to anon message
  __tests__/database/schema/ChatSchema.test.ts
  src/database/schema/ChatSchema.ts
Labels: need review, merge to staging

#2207 fix: ping-3926 message double/redundant on anon to anon message
  __tests__/database/schema/ChatSchema.test.ts
  src/database/schema/ChatSchema.ts
Labels: need review, merge to main

#2209 [PING-3925] fix: vote color
  src/components/Comments/Comment.js
  src/components/Comments/ReplyCommentItem.js
  src/components/Footer/Footer.js
  src/utils/theme/index.js
Labels: need review, merge to main

#2216 fix: ping-3934 ping-3935 pn on app open and open when receiver anon
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to staging

#2215 fix: ping-3934 ping-3935 pn on app open and open when receiver anon
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to main

#2225 fix: no need to fetch channel detail when open chat from push notif
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to staging

#2226 feat: ping-3969 remove pn are read already
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to staging

#2227 [PING-3818] feat: improved commenting flow
  __tests__/components/Comments/ContainerComment.test.js
  src/components/Comments/Comment.js
  src/components/Comments/ConnectorWrapper.js
  src/components/Comments/ContainerComment.js
  src/components/Comments/ListComment.js
  src/components/Comments/WriteComment.js
  src/components/PostPageDetail/index.js
  src/screens/PostPageDetail/index.js
Labels: need review, merge to staging

#2229 fix: upgrade async storage to prevent crash
  ios/Helio.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/hooks/context/useResetContext.js
  src/screens/TopicPageScreen/index.js
  yarn.lock
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2231 Fix/ping 3358 topic
  __tests__/database/migration/file/index.test.ts
  __tests__/database/migration/index.test.ts
  __tests__/database/schema/ChannelListSchema.test.ts
  src/components/ChatList/CommunityChannelItem.tsx
  src/components/ChatList/hook/useTopicChannelItemHook.ts
  src/database/hooks/useLocalDatabaseHook.js
  src/database/migration/file/index.ts
  src/database/migration/file/migration_version_22_channel_list_add_topic_post_expired_at.ts
  src/database/migration/index.ts
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/websocket/types.d.ts
  src/hooks/screen/useSignedChannelListHook.ts
  src/screens/ChannelListScreen/index.tsx
  src/service/topics.ts
  src/utils/log/FeatureLog.ts
  types/component/ChatList/ChannelItem.types.ts
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
  types/repo/AnonymousMessageRepo/AnonymousChannelsData.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2237 fix: change fcm token delete url to v2
  __tests__/hooks/useSettings.test.js
  src/screens/Settings/hooks/useSettings.js
  src/service/users.js
Labels: need review, merge to staging, on testing

#2230 fix: upgrade async storage to prevent crash
  ios/Helio.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/hooks/context/useResetContext.js
  src/screens/TopicPageScreen/index.js
  yarn.lock
Labels: need review, merge to main, waiting for visual feedback, on testing

#2243 Merge/ping 3995 news
  __tests__/screens/News/Search.test.js
  __tests__/screens/News/__snapshots__/Search.test.js.snap
  src/navigations/HomeBottomTabs.js
  src/navigations/root-stack.js
  src/screens/GroupInfo/elements/ModalAction.js
  src/screens/NewsScreen/Search.js
  src/screens/NewsScreen/index.js
  src/screens/Settings/index.js
Labels: need review, merge to staging, on testing

#2219 fix: no need to fetch channel detail when open chat from push notif
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to main

#2257 fix: ping-3966 chat screen is loading slow, and reloading every time i go to the chat
  App.js
  ios/Podfile.lock
  package.json
  src/hooks/screen/services/chatScreenHooks.js
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChatScreen/SignedChatScreen.tsx
  types/hooks/screens/useChatScreenHook.types.ts
  yarn.lock
Labels: need review, merge to staging

#2238 fix: change fcm token delete url to v2
  __tests__/hooks/useSettings.test.js
  src/screens/Settings/hooks/useSettings.js
  src/service/users.js
Labels: need review, merge to main, on testing

#2260 chore: upgrade human ID version to 2.4.11
  ios/Podfile.lock
  package.json
  src/screens/SignInV2/index.js
  yarn.lock
Labels: need review, merge to staging, on testing

#2264 [PING-3850] fix: write comment and comment style
  __tests__/components/Comments/WriteComment.test.js
  src/components/Comments/WriteComment.js
  src/components/PostPageDetail/index.js
  src/service/comment.js
Labels: need review, merge to staging

#2265 [PING-3849] fix: comment text behavior
  src/components/CommentUsername/CommentUsername.js
  src/components/Comments/Comment.js
Labels: need review, merge to staging

#2256 fix: ping-3966 chat screen is loading slow, and reloading every time i go to the chat
  App.js
  ios/Podfile.lock
  package.json
  src/hooks/screen/services/chatScreenHooks.js
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChatScreen/SignedChatScreen.tsx
  types/hooks/screens/useChatScreenHook.types.ts
  yarn.lock
Labels: need review, merge to main

#2267 feat: ping-3996 my profile not aligned
  src/screens/ProfileScreen/elements/KarmaLock.tsx
Labels: need review, waiting for visual feedback, merge to staging

#2263 Merge/ping 3985
  src/core/queue/DatabaseQueue.ts
  src/database/schema/ChannelListSchema.ts
  src/hooks/appBadge/useAppBadgeHook.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/navigations/HomeBottomTabs.js
Labels: need review, merge to staging, on testing

#2277 feat: ping-3998 clickable link on chat screen
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/LinkableText.tsx
  src/utils/theme/index.js
Labels: need review, merge to staging

#2271 [PING-3556] fix: community page header design
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#2280 [PING-3607] fix: credder score pdp
  src/components/CredderRating/FeedCredderRating.js
  src/components/PostPageDetail/elements/Content.js
Labels: need review, merge to staging

#2228 [PING-3818] feat: improved commenting flow
  __tests__/components/Comments/ContainerComment.test.js
  __tests__/components/Comments/WriteComment.test.js
  src/components/CommentUsername/CommentUsername.js
  src/components/Comments/Comment.js
  src/components/Comments/ConnectorWrapper.js
  src/components/Comments/ContainerComment.js
  src/components/Comments/ListComment.js
  src/components/Comments/WriteComment.js
  src/components/PostPageDetail/index.js
  src/screens/PostPageDetail/index.js
  src/service/comment.js
Labels: need review, merge to main

#2279 [PING-3732] fix: remove connector last comment
  src/components/Comments/ContainerComment.js
Labels: need review, merge to main

#2281 [PING-3607] fix: credder score pdp
  src/components/CredderRating/FeedCredderRating.js
  src/components/PostPageDetail/elements/Content.js
Labels: need review, merge to main

#2262 feat: add badge number on home
  src/core/queue/DatabaseQueue.ts
  src/database/schema/ChannelListSchema.ts
  src/hooks/appBadge/useAppBadgeHook.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/navigations/HomeBottomTabs.js
Labels: need review, merge to main, on testing

#2269 fix: enable news on settings
  src/screens/Settings/index.js
Labels: merge to main

#2287 fix: change bottom tab name
  src/navigations/HomeBottomTabs.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2288 feat: ping-3998 add clickable link on other chat
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
Labels: need review, merge to staging

#2286 fix: change bottom tab name
  src/navigations/HomeBottomTabs.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2290 fix: delete fcm token before deleting local storage
  src/screens/Settings/hooks/useSettings.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2291 fix: change demo verify user endpoint
  src/components/DevDummyLogin/index.js
  src/service/users.js
Labels: need review, merge to staging, on testing

#2293 Merge/ping 3358
  src/core/queue/DatabaseQueue.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/screen/useSignedChannelListHook.ts
  src/service/topics.ts
Labels: need review, merge to staging, on testing

#2294 [PING-3556] fix: community header design
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#2295 [PING-3950] fix: comment preview if emoji
  src/components/ReadMore/index.js
  src/screens/ProfileScreen/elements/TextWithEmoji.tsx
Labels: need review, merge to staging

#2292 fix: change demo verify user endpoint
  src/components/DevDummyLogin/index.js
  src/service/users.js
Labels: need review, merge to main, on testing

#2261 chore: upgrade human ID version to 2.4.11
  ios/Podfile.lock
  package.json
  src/screens/SignInV2/index.js
  yarn.lock
Labels: need review, merge to main, on testing

#2296 [PING-3950] fix: comment preview if emoji
  src/components/ReadMore/index.js
  src/screens/ProfileScreen/elements/TextWithEmoji.tsx
Labels: need review, merge to main

#2232 Fix/ping 3358 topic
  __tests__/database/migration/file/index.test.ts
  __tests__/database/migration/index.test.ts
  __tests__/database/schema/ChannelListSchema.test.ts
  src/components/ChatList/CommunityChannelItem.tsx
  src/components/ChatList/hook/useTopicChannelItemHook.ts
  src/core/queue/DatabaseQueue.ts
  src/database/hooks/useLocalDatabaseHook.js
  src/database/migration/file/index.ts
  src/database/migration/file/migration_version_22_channel_list_add_topic_post_expired_at.ts
  src/database/migration/index.ts
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/websocket/types.d.ts
  src/hooks/screen/useSignedChannelListHook.ts
  src/screens/ChannelListScreen/index.tsx
  src/service/topics.ts
  src/utils/log/FeatureLog.ts
  types/component/ChatList/ChannelItem.types.ts
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
  types/repo/AnonymousMessageRepo/AnonymousChannelsData.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2299 [PING-3556] fix: community page header design
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main
