Repository BetterSocial/mobileapp, pull requests merged in 2024-07, with the labels that each got.

#2428 [PING-4153] fix: add shimmer on topic member count
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main

#2429 [PING-4165] fix: rollback show own profile in topic member list
  src/screens/TopicMemberScreen/index.js
Labels: need review, merge to main

#2439 fix: disabled v3 create community for release new prod version
  src/screens/CreateCommunity/index.js
Labels: need review, merge to main

#2444 fix: click effect follow in follower list PING-4164
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
Labels: need review, merge to staging

#2446 Merge/ping 4074
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/PreviewComment/index.js
  src/screens/FeedScreen/RenderList.js
Labels: need review, merge to staging, on testing

#2445 Fix/ping 4074 preview comment
  src/components/PreviewComment/index.js
  src/screens/FeedScreen/RenderList.js
Labels: need review, merge to main, on testing

#2456 feat: change emoji to chat description title
  src/components/Chat/InputMessageV2.tsx
Labels: need review, merge to staging, on testing

#2454 [PING-4162] feat: separate follower list
  src/screens/Followings/FollowersScreen.js
  src/screens/Followings/index.js
  src/screens/ProfileScreen/index.js
Labels: need review, merge to main

#2465 fix: add item for onDeletePost param and change delete anonymous post…
  src/screens/FeedScreen/Header.js
  src/service/post.js
Labels: need review, merge to staging, on testing

#2455 feat: change emoji to chat description title
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/MessageChannelItem.tsx
  src/components/AnonymousChat/child/ChannelTitle.tsx
  src/components/Chat/InputMessageV2.tsx
  types/component/AnonymousChat/BaseChannelItem.types.ts
Labels: need review, merge to main, on testing

#2468 fix: create post from karma lock component
  src/screens/CreatePost/index.js
  src/screens/ProfileScreen/index.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2470 Fix/ping 4131 pon
  ios/Helio.xcodeproj/project.pbxproj
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/AnonymousChat/child/ChannelTitle.tsx
  types/component/AnonymousChat/BaseChannelItem.types.ts
Labels: need review, merge to staging, on testing

#2447 feat: topic detection on text
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/LinkableText.tsx
  src/components/Text/LinkDetectionText.tsx
  src/components/Text/TopicDetectionOnChat.tsx
  src/utils/string/StringUtils.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2463 feat: add preview on channel list when changing group name
  src/components/ChatList/GroupChatChannelItem.tsx
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/websocket/types.d.ts
  types/component/ChatList/ChannelContent.types.ts
  types/database/schema/ChannelList.types.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2466 fix: create post from karma lock component
  src/screens/CreatePost/index.js
  src/screens/ProfileScreen/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2464 fix: add item for onDeletePost param and change delete anonymous post…
  src/screens/FeedScreen/Header.js
  src/service/post.js
Labels: need review, merge to main, on testing

#2462 feat: add preview on channel list when changing group name
  src/components/ChatList/GroupChatChannelItem.tsx
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/websocket/types.d.ts
  types/component/ChatList/ChannelContent.types.ts
  types/database/schema/ChannelList.types.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2471 fix: add notification.data.type topic to handle notification
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to main, on testing

#2472 fix: add notification.data.type topic to handle notification
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to staging, on testing

#2469 feat: italic media for post that has images and no messages
  __tests__/service/anonymousMessageRepo.test.ts
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/AnonymousChat/child/ChannelTitle.tsx
  src/service/feeds.js
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  types/component/AnonymousChat/BaseChannelItem.types.ts
Labels: need review, merge to main, on testing

#2483 fix: change margin top condition for nav header
  src/navigations/root-stack.js
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/ChatScreen/ChatScreen.styles.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/ChatScreen/useChatScreenDimensions.tsx
  src/screens/TopicPageScreen/elements/NavHeader.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2484 [PING-4158] fix: slow loading suggested communities
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/FeedScreen/index.js
Labels: need review, merge to staging

#2488 Fix/ping 3936 push notification
  android/app/build.gradle
  src/atom/currentChatScreenAtom.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/hooks/screen/useChatScreenHook.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2482 fix: change margin top condition for nav header
  src/navigations/root-stack.js
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/ChatScreen/ChatScreen.styles.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/ChatScreen/useChatScreenDimensions.tsx
  src/screens/TopicPageScreen/elements/NavHeader.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2367 feat: PING-4096 Chat Tabs Analytics
  __tests__/utils/share.test.js
  src/components/BlockComponent/index.js
  src/components/Blocking/BlockPostAnonymous.js
  src/components/Blocking/BlockUser.js
  src/components/Button/ButtonNewPost.js
  src/components/Chat/InputMessageV2.tsx
  src/components/Comments/Comment.js
  src/components/Comments/ContainerComment.js
  src/components/Comments/WriteComment.js
  src/components/Comments/hooks/useComment.js
  src/components/Footer/Footer.js
  src/components/PostPageDetail/index.js
  src/components/TopicsChip/TopicsChip.js
  src/hooks/core/post/usePostHook.tsx
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/libraries/analytics/analyticsEventTracking.ts
  src/libraries/analytics/useAnalyticUtilsHook.ts
  src/screens/ChannelListScreen/elements/Search.js
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentPoll.js
  src/screens/FeedScreen/Header.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/hooks/useContentPoll.js
  src/screens/FeedScreen/hooks/useFeedHeader.js
  src/screens/FeedScreen/hooks/useViewPostTimeHook.ts
  src/screens/FeedScreen/index.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/elements/BottomSheetFollow.tsx
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/index.js
  src/utils/constants/index.js
  src/utils/share/index.js
  types/hooks/screens/useAnonymousChatInfoScreenHook.types.ts
Labels: need review, merge to main, waiting for visual feedback, on testing
