Repository BetterSocial/mobileapp, pull requests merged in 2024-03, with the labels that each got.

#2003 fix: unhide memberlist anon
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/elements/TopicDomainHeader.js
Labels: need review, merge to staging

#2007 Fix/ping 3744
  src/utils/constants/index.js
Labels: need review, merge to staging, on testing

#2006 [PING-3224] fix: community search mismatch data
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#1999 fix: change feed diff value to fetch
  src/utils/constants/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2012 [PING-3224] fix: community search mismatch data
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main

#1982 fix: ping 3711 search gif broken
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/Chat/BottomSheetGif.js
  src/service/gif.js
  src/utils/permission/index.js
Labels: need review, merge to main

#2016 fix: ping-3762 weird auto fill on other profile staging
  src/components/TextAreaChat/index.tsx
Labels: need review, waiting for visual feedback, merge to staging

#2018 feat: ping-3757 other profile doesnt allow incognito messages-staging
  src/hooks/screen/useCreateChat.ts
  src/screens/OtherProfile/index.js
Labels: need review, waiting for visual feedback, merge to staging

#2011 Feat/migration anon topic
  __tests__/database/migration/file/index.test.ts
  __tests__/database/migration/index.test.ts
  src/database/migration/file/base_migration_v2.ts
  src/database/migration/file/index.ts
  src/database/migration/file/migration_version_18_channel_list_add_column_type_new.ts
  src/database/migration/file/migration_version_19_channel_list_copy_column_type_to_column_type_new.ts
  src/database/migration/file/migration_version_20_channel_list_delete_channel_type.ts
  src/database/migration/file/migration_version_21_channel_list_rename_column_type_new.ts
  src/database/migration/index.ts
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
Labels: need review, merge to main, on testing

#2015 fix: ping-3762 weird auto fill on other profile
  src/components/TextAreaChat/index.tsx
Labels: need review, merge to main

#2017 feat: ping-3757 other profile doesnt allow incognito messages
  src/hooks/screen/useCreateChat.ts
  src/screens/OtherProfile/index.js
Labels: need review, merge to main

#2025 Feat/ping 3263 start new anon chat staging
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  src/components/DevDummyLogin/index.js
  src/screens/ContactScreen/elements/RenderItem.js
  src/screens/ContactScreen/elements/Search.js
  src/screens/ContactScreen/index.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/PostPageDetail/index.js
  src/service/discovery.js
  src/service/users.js
Labels: need review, merge to staging

#2044 Feat/ping 3263 start new anon chat staging
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  src/assets/icons/Ic_Checklist.js
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/components/DevDummyLogin/index.js
  src/components/Header/HeaderContact.js
  src/components/Items/ProfileContact.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ContactScreen/elements/ItemUser.js
  src/screens/ContactScreen/elements/RenderItem.js
  src/screens/ContactScreen/elements/Search.js
  src/screens/ContactScreen/index.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/PostPageDetail/index.js
  src/service/discovery.js
  src/service/users.js
  src/utils/string/StringConstant/index.js
  src/utils/theme/index.js
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
Labels: need review, merge to staging

#2027 Fix/push notifications
  src/database/hooks/useLocalDatabaseHook.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/navigations/HomeBottomTabs.js
  src/navigations/root-stack.js
  types/hooks/screens/useChatUtilsHook.types.ts
Labels: need review, merge to main, on testing

#2050 fix: system message from registration
  src/hooks/core/chat/useFetchChannelHook.ts
Labels: need review, merge to staging, on testing

#2049 fix: system message from registration
  src/hooks/core/chat/useFetchChannelHook.ts
Labels: need review, merge to main, on testing

#2013 Feat/ping 3263 start new anon chat main
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  src/assets/icons/Ic_Checklist.js
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/components/DevDummyLogin/index.js
  src/components/Header/HeaderContact.js
  src/components/Items/ProfileContact.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ContactScreen/elements/ItemUser.js
  src/screens/ContactScreen/elements/RenderItem.js
  src/screens/ContactScreen/elements/Search.js
  src/screens/ContactScreen/index.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/PostPageDetail/index.js
  src/service/discovery.js
  src/service/users.js
  src/utils/string/StringConstant/index.js
  src/utils/theme/index.js
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
Labels: need review, merge to main, on testing

#2055 [PING-2508] feat: community anon follow
  src/assets/dp-topics-anon.png
  src/assets/dp-topics-signed.png
  src/assets/icon/IconCheckCircleOutline.tsx
  src/assets/icon/IconClose.tsx
  src/assets/icon/IconIncognito.tsx
  src/assets/icon/PostToCommunity.js
  src/components/BottomSheet/BottomSheetV2.tsx
  src/components/BottomSheet/index.js
  src/components/Button/ButtonAddPostTopic.js
  src/screens/CreatePost/elements/UserProfile.js
  src/screens/CreatePost/index.js
  src/screens/TopicMemberScreen/elements/TopicMemberHeadlineList.tsx
  src/screens/TopicMemberScreen/index.js
  src/screens/TopicPageScreen/elements/BottomSheetFollow.tsx
  src/screens/TopicPageScreen/elements/ButtonFollowing.js
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/elements/TopicDomainHeader.js
  src/screens/TopicPageScreen/elements/UserItem.tsx
  src/screens/TopicPageScreen/index.js
  src/service/topics.js
  src/utils/getstream/useChatClientHook.js
Labels: merge to staging

#2059 fix: push notification dialog not showing
  src/hooks/context/useResetContext.js
  src/hooks/screen/useRootChannelListHook.ts
  src/screens/Settings/hooks/useSettings.js
  src/utils/constants/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2062 [PING-3545] fix: topic memberlist scrolling weird
  src/screens/TopicMemberScreen/index.js
Labels: need review, merge to staging

#2068 fix: PING-3778 add hashtag after fallback topic name value
  src/utils/string/StringUtils.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2069 [PING-3545] fix: topic memberlist scrolling weird
  src/screens/TopicMemberScreen/index.js
Labels: need review, merge to main

#2071 fix: ping-3807 padding bellow dp
  src/screens/ProfileScreen/elements/FollowInfoRow.js
  src/screens/ProfileScreen/index.js
Labels: need review, waiting for visual feedback, merge to staging

#2073 fix: ping-3777 view dp not working
  src/screens/ProfileScreen/index.js
Labels: need review, merge to staging

#2075 fix: ping-3776 change resize mode from stretch to cover
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#2064 [PING-3789] fix: create post default anon toggle
  src/screens/CreatePost/index.js
Labels: need review, merge to staging

#2070 fix: ping-3807 padding bellow dp
  src/screens/ProfileScreen/elements/FollowInfoRow.js
  src/screens/ProfileScreen/index.js
Labels: need review, merge to main

#2072 fix: ping-3777 view dp not working
  src/screens/ProfileScreen/index.js
Labels: need review, merge to main

#2074 fix: ping-3776 change resize mode from stretch to cover
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to main

#2067 fix: PING-3778 add hashtag after fallback topic name value
  src/utils/string/StringUtils.js
Labels: need review, merge to main, on testing

#2084 feat: ping-3806 fix share button
  src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
Labels: need review, merge to staging

#2085 [PING-3395] fix: single poll calculation
  src/screens/FeedScreen/ContentPoll.js
Labels: need review, merge to staging

#2087 Fix/ping 3721 wrong wording when following users
  __tests__/hooks/useGroupInfo.test.js
  src/hooks/core/auth/useUserAuthHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/chat/useSystemMessage.ts
  src/hooks/core/profile/useProfileHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/core/websocket/types.d.ts
  src/screens/CreatePost/index.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/service/post.js
  src/service/profile.js
  src/service/topics.js
Labels: need review, merge to staging, on testing

#2088 [PING-3395] fix: single poll calculation
  src/screens/FeedScreen/ContentPoll.js
Labels: need review, merge to main

#2081 feat: ping-3806 fix share button
  src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
Labels: need review, merge to main

#2100 fix: ping 3862 media not showing up on recipient side staging
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemAttachment.tsx
  src/components/AnonymousChat/child/ChatItemAttachmentStyles.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
Labels: need review, merge to staging

#2094 fix: ping-3752 profile bio font style wrong
  ios/Podfile.lock
  package.json
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
  src/screens/ProfileScreen/elements/TextWithEmoji.tsx
  yarn.lock
Labels: need review, merge to staging

#2109 feat: ping-3712 dp not center
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#2107 feat: ping-3753 center headlines
  src/components/Header/index.js
Labels: need review, merge to staging

#2103 fix: hide block button if my comment and my post
  src/components/Comments/Comment.js
  src/components/Comments/ReplyCommentItem.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2086 Fix/ping 3721 wrong wording when following users
  __tests__/hooks/useGroupInfo.test.js
  src/hooks/core/auth/useUserAuthHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/chat/useSystemMessage.ts
  src/hooks/core/profile/useProfileHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/core/websocket/types.d.ts
  src/screens/CreatePost/index.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/service/post.js
  src/service/profile.js
  src/service/topics.js
Labels: need review, merge to main, on testing

#2105 Core - Add Privacy Info to fix warning on App Store
  ios/Helio.xcodeproj/project.pbxproj
  ios/PrivacyInfo.xcprivacy
Labels: merge to staging

#2099 fix: ping 3826 media not showing up on recipient side main
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemAttachment.tsx
  src/components/AnonymousChat/child/ChatItemAttachmentStyles.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
Labels: need review, merge to main

#2093 fix: ping-3752 profile bio font style wrong
  ios/Podfile.lock
  package.json
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
  src/screens/ProfileScreen/elements/TextWithEmoji.tsx
  yarn.lock
Labels: need review, merge to main

#2106 feat: ping-3753 center headlines
  src/components/Header/index.js
Labels: need review, merge to main

#2097 Fix/ping 3770 crash android main
  ios/Podfile.lock
  package.json
  src/screens/FeedScreen/elements/BlurredLayer.js
  yarn.lock
Labels: need review, merge to main

#2117 [PING-3795] fix: discovery fetch after follow
  src/screens/TopicPageScreen/elements/BottomSheetFollow.tsx
Labels: need review, merge to staging

#2102 fix: hide block button if my comment and my post
  src/components/Comments/Comment.js
  src/components/Comments/ReplyCommentItem.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2131 fix: ping-3712 dp not centered
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#2130 Feat/epic ping 3562 bring back chat features staging
  __tests__/hooks/useGroupInfo.test.js
  src/assets/images/default-chat-group-picture.png
  src/components/ChatList/GroupChatChannelItem.tsx
  src/components/Header/HeaderContact.js
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useSystemMessage.ts
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/ContactScreen/index.js
  src/screens/GroupInfo/elements/ModalAction.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/GroupInfo/index.js
  src/screens/GroupSetting/index.js
  src/service/chat.js
  src/utils/string/StringUtils.js
Labels: need review, merge to staging

#2133 fix: ping-3834 discovery recent in wrong color
  src/screens/DiscoveryScreenV2/elements/RecentSearch.js
Labels: need review, merge to staging

#2123 fix: change anonymous tab color in profile to anonprimary
  src/screens/ProfileScreen/elements/AnonymousTab.js
  src/screens/ProfileScreen/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2116 Fix/ping 3821 text bottom bar
  __tests__/screens/ChannelListScreenV2/ChannelListScreenV2.test.js
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  src/navigations/HomeBottomTabs.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2000 [PING-2508] feat: community anon follow
  src/assets/dp-topics-anon.png
  src/assets/dp-topics-signed.png
  src/assets/icon/IconCheckCircleOutline.tsx
  src/assets/icon/IconClose.tsx
  src/assets/icon/IconIncognito.tsx
  src/assets/icon/PostToCommunity.js
  src/components/BottomSheet/BottomSheetV2.tsx
  src/components/BottomSheet/index.js
  src/components/Button/ButtonAddPostTopic.js
  src/screens/CreatePost/elements/UserProfile.js
  src/screens/CreatePost/index.js
  src/screens/TopicMemberScreen/elements/TopicMemberHeadlineList.tsx
  src/screens/TopicMemberScreen/index.js
  src/screens/TopicPageScreen/elements/BottomSheetFollow.tsx
  src/screens/TopicPageScreen/elements/ButtonFollowing.js
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/elements/TopicDomainHeader.js
  src/screens/TopicPageScreen/elements/UserItem.tsx
  src/screens/TopicPageScreen/index.js
  src/service/topics.js
  src/utils/getstream/useChatClientHook.js
Labels: need review, merge to main

#2108 feat: ping-3712 dp not center
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to main

#2132 fix: ping-3834 discovery recent in wrong color
  src/screens/DiscoveryScreenV2/elements/RecentSearch.js
Labels: need review, merge to main

#2136 Merge/ping 3835
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelTitle.test.tsx.snap
  src/components/AnonymousChat/child/ChannelTitle.tsx
  src/components/PostPageDetail/index.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useSystemMessage.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/utils/log/FeatureLog.ts
Labels: need review, merge to staging, on testing

#2142 [PING-3742] fix: default image community
  src/assets/dp-topics-anon.png
  src/assets/dp-topics-signed.png
  src/screens/TopicPageScreen/elements/NavHeader.js
Labels: need review, merge to staging

#2135 Fix/ping 3835 message not updating
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelTitle.test.tsx.snap
  __tests__/hooks/useFeedHeader.test.js
  __tests__/screens/FeedScreen/HeaderFeed.test.js
  src/components/AnonymousChat/child/ChannelTitle.tsx
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useSystemMessage.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/utils/log/FeatureLog.ts
Labels: need review, merge to main, on testing

#2144 Feat/epic ping 3562 bring back chat features staging
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/GroupInfo/hooks/useGroupInfo.js
Labels: need review, merge to staging

#2126 Feat/epic ping 3562 bring back chat features main
  __tests__/hooks/useGroupInfo.test.js
  src/assets/images/default-chat-group-picture.png
  src/components/ChatList/GroupChatChannelItem.tsx
  src/components/Header/HeaderContact.js
  src/components/PostPageDetail/elements/Content.js
  src/database/schema/UserSchema.ts
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/ContactScreen/index.js
  src/screens/GroupInfo/elements/ModalAction.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/GroupInfo/index.js
  src/screens/GroupSetting/index.js
  src/service/chat.js
  src/utils/string/StringUtils.js
Labels: need review, merge to main

#2104 Core - Add Privacy Info to fix warning on App Store
  ios/Helio.xcodeproj/project.pbxproj
  ios/PrivacyInfo.xcprivacy
Labels: merge to main

#2143 [PING-3742] fix: default image community
  src/assets/dp-topics-anon.png
  src/assets/dp-topics-signed.png
  src/screens/TopicPageScreen/elements/NavHeader.js
Labels: need review, merge to main

#2151 Feat/ping 3360 who to follow v2 staging
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowLabel.test.js.snap
  __tests__/components/WhoToFollow/__snapshots__/WhoToFollowUserInfo.test.js.snap
  src/assets/icon/IconAdd.js
  src/assets/icon/IconCheck.js
  src/screens/WhotoFollow/elements/ItemUser.js
  src/screens/WhotoFollow/elements/Label.js
  src/screens/WhotoFollow/elements/UserInfo.js
  src/screens/WhotoFollow/index.js
  src/service/topics.js
Labels: need review, waiting for visual feedback, merge to staging

#2152 Fix/ping 3828 chat not showing
  src/core/queue/BaseQueue.ts
  src/database/hooks/useSaveAnonChatHook.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/utils/log/FeatureLog.ts
Labels: need review

#2157 [PING-3675] fix: disabled button when click post
  src/screens/CreatePost/index.js
Labels: need review, merge to staging

#2148 Fix/ping 3688 incognito checkbox
  __tests__/hooks/useFeedHeader.test.js
  __tests__/screens/FeedScreen/HeaderFeed.test.js
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2154 chore: update privacy setting
  ios/PrivacyInfo.xcprivacy
Labels: merge to main

#2153 chore: update privacy setting
  ios/PrivacyInfo.xcprivacy
Labels: merge to staging

#2158 [PING-3675] fix: post got error message but success create
  src/screens/CreatePost/index.js
Labels: need review, merge to main

#2159 Fix/ping 3828 chat not showing
  ios/Helio.xcodeproj/project.pbxproj
  src/components/AnonymousChat/BaseChatItem.tsx
  src/core/queue/BaseQueue.ts
  src/core/queue/DatabaseQueue.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/utils/string/StringUtils.js
  types/hooks/screens/useChatUtilsHook.types.ts
Labels: need review, on testing

#2168 New App logo (Main)
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
  ios/Helio.xcodeproj/project.pbxproj
Labels: merge to main

#2171 Main ping 3775
  __tests__/components/AnonymousChat/__snapshots__/AnonymousChatHeader.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelTitle.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/Blocking/__snapshots__/SpecificIssue.test.js.snap
  __tests__/components/Button/__snapshots__/ButtonAddTopicPost.test.js.snap
  __tests__/database/schema/UserSchema.test.ts
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  ios/Helio.xcodeproj/project.pbxproj
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/core/queue/BaseQueue.ts
  src/core/queue/DatabaseQueue.ts
  src/database/hooks/useLocalDatabaseHook.js
  src/database/hooks/useSaveAnonChatHook.ts
  src/database/schema/ChatSchema.ts
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/chat/useFetchPostNotificationHook.ts
  src/hooks/core/queue/useDatabaseQueueHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/hooks/useInitialStartup.js
  src/navigations/HomeBottomTabs.js
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  src/utils/log/FeatureLog.ts
  src/utils/storage/index.ts
  src/utils/string/StringUtils.js
  src/utils/theme/index.js
  src/utils/users/index.js
  types/database/localDatabase.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
Labels: need review, merge to main, on testing

#2173 Fix/ping 3876 staging
  src/screens/CreatePost/index.js
Labels: need review, merge to staging
