Repository BetterSocial/mobileapp, pull requests merged in 2024-01, with the labels that each got.

#1773 Merge/ping 3066
  src/components/AnonymousChat/ChatDetailHeader.tsx
Labels: need review, merge to staging

#1719 Feat-774 main
  __tests__/components/Button/__snapshots__/ButtonAddTopicPost.test.js.snap
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/DiscoveryScreenV2/Search.test.js
  __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  declaration.d.ts
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/assets/arrow/Ic_arrow_back_circle.js
  src/assets/icon/CommunityIcon.tsx
  src/components/Button/ButtonAddPostTopic.js
  src/components/Header/HeaderContact.js
  src/components/PostPageDetail/index.js
  src/components/Shimmer/Shimmer.tsx
  src/components/TiktokScroll/index.js
  src/context/actions/feeds.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/navigations/HomeBottomTabs.js
  src/navigations/KeyboardWrapper.tsx
  src/navigations/root-stack.js
  src/screens/ChannelListScreenV2/index.tsx
  src/screens/ContactScreen/index.js
  src/screens/DiscoveryScreenV2/elements/Search.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/FeedScreen/index.js
  src/screens/NewsScreen/index.js
  src/screens/ProfileScreen/index.js
  src/screens/TopicMemberScreen/index.js
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/elements/TopicDomainHeader.js
  src/screens/TopicPageScreen/index.js
  yarn.lock
Labels: merge to main

#1777 fix: ping-3434 edit prompt staging
  src/components/BottomSheet/BottomSheet.js
  src/screens/ProfileScreen/elements/BottomSheetBio.js
Labels: need review, merge to staging

#1772 feat: PING-3509 PING-3510 PING-3514
  __tests__/components/FeedItem/FeedItem.test.js
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/Comments/WriteComment.js
  src/components/PostPageDetail/index.js
  src/components/ToggleSwitch/index.tsx
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentLink.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/index.js
  src/screens/OtherProfile/index.js
  src/screens/OtherProfilePostDetail/index.js
  src/screens/PostPageDetail/index.js
  src/screens/ProfileScreen/elements/RenderItem.js
  src/screens/ProfileScreen/index.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#1690 (Main) PING 3434 fix promp edit bio
  __tests__/components/Blocking/__snapshots__/SpecificIssue.test.js.snap
  ios/Podfile.lock
  src/components/BottomSheet/BottomSheet.js
  src/components/Button/Button.js
  src/components/Karma/GradientCircularProgress.tsx
  src/components/TextArea/AutoFocusTextArea.js
  src/screens/CreatePost/elements/SheetCloseBtn.js
  src/screens/LocalCommunity/index.js
  src/screens/ProfileScreen/elements/BottomSheetBio.js
  src/screens/ProfileScreen/index.js
  src/screens/Topics/index.js
Labels: need review, merge to main

#1762 feat: ping 2727 handle offline button staging
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/service/profile.js
Labels: need review, merge to staging

#1779 Ping 3072 Fix Feedback Global Color
  __tests__/components/Tabbar/Tabbar.test.js
  __tests__/database/migration/file/index.test.ts
  __tests__/database/migration/index.test.ts
  __tests__/database/schema/ChannelListSchema.test.ts
  __tests__/database/schema/UserSchema.test.ts
  __tests__/hooks/useContentPoll.test.js
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/ChatDetailHeader.tsx
  src/components/BottomSheet/BottomSheetMenu.js
  src/components/Chat/InputMessageV2.tsx
  src/components/Chat/SheetEmoji.tsx
  src/components/Comments/WriteComment.js
  src/components/Items/ProfileContact.js
  src/components/Karma/GradientCircularProgress.tsx
  src/components/SendIcon/index.tsx
  src/components/TextAreaChat/index.tsx
  src/configs/ToastConfig.js
  src/database/hooks/useLocalDatabaseHook.js
  src/database/migration/file/index.ts
  src/database/migration/file/migration_version_10_users_add_anon_user_info_color_name.ts
  src/database/migration/file/migration_version_11_users_add_anon_user_info_color_code.ts
  src/database/migration/file/migration_version_12_channel_lists_add_anon_user_info_emoji_name.ts
  src/database/migration/file/migration_version_13_channel_lists_add_anon_user_info_emoji_code.ts
  src/database/migration/file/migration_version_14_channel_lists_add_anon_user_info_color_name.ts
  src/database/migration/file/migration_version_15_channel_lists_add_anon_user_info_color_code.ts
  src/database/migration/file/migration_version_8_users_add_anon_user_info_emoji_name.ts
  src/database/migration/file/migration_version_9_users_add_anon_user_info_emoji_code.ts
  src/database/migration/index.ts
  src/database/schema/ChannelListMemberSchema.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/ChatSchema.ts
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/screens/AnonymousChatScreen/index.tsx
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/FeedScreen/Header.js
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/OtherProfile/elements/BioAndChat.js
  src/screens/ProfileScreen/elements/KarmaScore.tsx
  src/screens/ProfileScreen/index.js
  src/utils/constants/index.js
  src/utils/string/StringUtils.js
  src/utils/theme/index.js
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useChatScreenHook.types.ts
  types/service/AnonProfile.type.ts
Labels: need review, merge to staging

#1782 PING 3363 - fix background topic chip
  src/components/TopicsChip/TopicsChip.js
Labels: merge to main

#1781 Ping 3072 - Fix toast color
  src/configs/ToastConfig.js
  src/utils/theme/index.js
Labels: need review, merge to staging

#1761 feat: ping 2727 handle offline button
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/service/profile.js
Labels: need review, merge to main

#1791 fix: search placeholder discovery staging
  src/screens/FeedScreen/elements/Search.js
Labels: need review, merge to staging

#1790 fix: search placeholder discovery main
  src/screens/FeedScreen/elements/Search.js
Labels: need review, merge to main

#1793 feat: karma circle refactor ping-3529 ping-3530 ping-3525
  ios/Podfile.lock
  src/components/Karma/utils.ts
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/KarmaScore.tsx
  src/screens/ProfileScreen/elements/ProfilePicture.js
  src/screens/ProfileScreen/index.js
Labels: need review, merge to staging

#1792 feat: userlist improvement staging
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/Followings/index.js
  src/service/discovery.js
Labels: need review, merge to staging

#1794 Feat/migration for fix emoji
  __tests__/database/migration/file/index.test.ts
  __tests__/database/migration/index.test.ts
  src/database/hooks/useLocalDatabaseHook.js
  src/database/migration/file/index.ts
  src/database/migration/file/migration_version_10_users_add_anon_user_info_color_name.ts
  src/database/migration/file/migration_version_11_users_add_anon_user_info_color_code.ts
  src/database/migration/file/migration_version_12_channel_lists_add_anon_user_info_emoji_name.ts
  src/database/migration/file/migration_version_13_channel_lists_add_anon_user_info_emoji_code.ts
  src/database/migration/file/migration_version_14_channel_lists_add_anon_user_info_color_name.ts
  src/database/migration/file/migration_version_15_channel_lists_add_anon_user_info_color_code.ts
  src/database/migration/file/migration_version_16_users_add_anon_user_info_emoji_name.ts
  src/database/migration/file/migration_version_8_change_enum_to_text.ts
  src/database/migration/file/migration_version_9_users_add_anon_user_info_emoji_code.ts
  src/database/migration/index.ts
Labels: need review, merge to staging, on testing

#1801 feat: ping-3468 enable suggestion staging
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
Labels: need review, waiting for visual feedback, merge to staging

#1804 Fix color footer feed icon (Feedback Bastian)
  src/assets/arrow/Ic_downvote_off.js
  src/assets/arrow/Ic_downvote_on.js
  src/assets/arrow/Ic_upvote_off.js
  src/assets/arrow/Ic_upvote_on.js
  src/assets/block/Ic_block_inactive.js
  src/assets/icons/Ic_comment.js
  src/assets/icons/Ic_share.js
  src/assets/icons/ic_globe.js
  src/utils/theme/index.js
Labels: need review, merge to staging

#1803 Fix color feedback on footer feed
  src/assets/arrow/Ic_downvote_off.js
  src/assets/arrow/Ic_downvote_on.js
  src/assets/arrow/Ic_upvote_off.js
  src/assets/arrow/Ic_upvote_on.js
  src/assets/block/Ic_block_inactive.js
  src/assets/icons/Ic_comment.js
  src/assets/icons/Ic_share.js
  src/assets/icons/ic_globe.js
  src/utils/theme/index.js
Labels: need review, merge to main

#1787 feat: user list improvement
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/Followings/index.js
  src/service/discovery.js
Labels: need review, merge to main

#1800 feat: ping-3468 enable suggestion
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
Labels: need review, merge to main, waiting for visual feedback

#1795 feat: migration for fixing emoji
  __tests__/database/migration/file/index.test.ts
  __tests__/database/migration/index.test.ts
  src/database/hooks/useLocalDatabaseHook.js
  src/database/migration/file/index.ts
  src/database/migration/file/migration_version_10_users_add_anon_user_info_color_name.ts
  src/database/migration/file/migration_version_11_users_add_anon_user_info_color_code.ts
  src/database/migration/file/migration_version_12_channel_lists_add_anon_user_info_emoji_name.ts
  src/database/migration/file/migration_version_13_channel_lists_add_anon_user_info_emoji_code.ts
  src/database/migration/file/migration_version_14_channel_lists_add_anon_user_info_color_name.ts
  src/database/migration/file/migration_version_15_channel_lists_add_anon_user_info_color_code.ts
  src/database/migration/file/migration_version_16_users_add_anon_user_info_emoji_name.ts
  src/database/migration/file/migration_version_8_change_enum_to_text.ts
  src/database/migration/file/migration_version_9_users_add_anon_user_info_emoji_code.ts
  src/database/migration/index.ts
Labels: need review, merge to main, on testing

#1812 Fix button join page color on community page
  src/screens/TopicPageScreen/elements/ButtonFollow.js
Labels: need review, merge to staging

#1815 Ping 3364 change topic chip bg to transparent
  src/components/TopicsChip/TopicsChip.js
  src/utils/theme/index.js
Labels: merge to main

#1811 Fix button join page color on community page
  src/screens/TopicPageScreen/elements/ButtonFollow.js
Labels: need review, merge to main

#1806 Merge/separate chat tab
  __tests__/screens/Blocked/RenderBlock.test.js
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/assets/icon/AnonymousChatFill.tsx
  src/assets/icon/AnonymousChatOutline.tsx
  src/assets/icon/SignedChat.tsx
  src/assets/images/AnonymousProfile.png
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/constant/index.ts
  src/hooks/screen/useAnonymousChannelListHook.ts
  src/hooks/screen/useRootChannelListHook.ts
  src/hooks/screen/useSignedChannelListHook.ts
  src/navigations/HomeBottomTabs.js
  src/navigations/root-stack.js
  src/screens/ChannelListScreen/elements/Search.js
  src/screens/ChannelListScreen/index.tsx
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/Settings/index.js
  src/screens/WebsocketResearchScreen/index.tsx
  src/utils/storage/index.ts
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
Labels: need review, merge to staging, on testing

#1817 Merge/fix emoji
  __tests__/database/schema/ChannelListSchema.test.ts
  __tests__/database/schema/UserSchema.test.ts
  __tests__/hooks/useGroupInfo.test.js
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/Items/ProfileContact.js
  src/database/schema/ChannelListMemberSchema.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/ChatSchema.ts
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/utils/constants/index.js
  src/utils/string/StringUtils.js
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useChatScreenHook.types.ts
  types/service/AnonProfile.type.ts
Labels: need review, merge to staging, on testing

#1810 fix: discovery tap behavior and safe area follower
  src/components/Button/Button.js
  src/navigations/root-stack.js
  src/screens/CreatePost/elements/SheetCloseBtn.js
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/Followings/index.js
  src/screens/ProfileScreen/elements/BottomSheetBio.js
Labels: need review, merge to staging

#1820 feat: ping-3526 add karma on other component staging
  src/components/AnonymousAvatar/index.js
  src/components/Comments/Comment.js
  src/components/Comments/ReplyCommentItem.js
  src/screens/FeedScreen/Header.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, waiting for visual feedback, merge to staging

#1823 fix: show circle karma component on anon user staging
  src/components/PreviewComment/index.js
  src/screens/FeedScreen/Header.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#1825 feat/ping-3391-blurred-post-staging
  __tests__/components/AnonymousAvatar/__snapshots__/index.test.js.snap
  __tests__/screens/Blocked/RenderBlock.test.js
  src/components/Footer/Footer.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/Header.js
  src/screens/FeedScreen/RenderList.js
Labels: need review, merge to staging

#1816 feat: init ping-3100 1b and 1c
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/Comments/WriteComment.js
  src/components/PostPageDetail/index.js
  src/components/ToggleSwitch/index.tsx
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentLink.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/index.js
  src/screens/OtherProfile/index.js
  src/screens/OtherProfilePostDetail/index.js
  src/screens/PostPageDetail/index.js
  src/screens/ProfileScreen/elements/RenderItem.js
  src/screens/ProfileScreen/index.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#1826 Feat/fix emoji
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/MessageChannelItem.tsx
  src/components/AnonymousChat/child/ChannelAnonymousImage.tsx
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/components/Chat/InputMessageV2.tsx
  src/database/hooks/useSaveAnonChatHook.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/ChatSchema.ts
  src/hooks/core/chat/useMoveChatTypeHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/core/websocket/types.d.ts
  src/hooks/screen/useChatScreenHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/utils/string/StringUtils.js
  types/component/AnonymousChat/BaseChannelItem.types.ts
  types/service/AnonProfile.type.ts
Labels: need review, merge to staging, on testing

#1827 fix: add comment preview button color
  src/components/Comments/WriteComment.js
Labels: need review, merge to staging

#1784 feat: karma circle refactor ping-3529 ping-3530 ping-3525
  src/components/Karma/utils.ts
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/KarmaScore.tsx
  src/screens/ProfileScreen/elements/ProfilePicture.js
  src/screens/ProfileScreen/index.js
Labels: need review, merge to main

#1809 fix: discovery tap behavior and safe area follower
  src/components/Button/Button.js
  src/navigations/root-stack.js
  src/screens/CreatePost/elements/SheetCloseBtn.js
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/DiscoveryScreenV2/fragment/UsersFragment.js
  src/screens/Followings/index.js
  src/screens/ProfileScreen/elements/BottomSheetBio.js
Labels: need review, merge to main

#1829 fix: feed not updated automatically
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to staging

#1830 fix: feedback pairing
  __tests__/database/schema/ChannelListSchema.test.ts
  __tests__/database/schema/UserSchema.test.ts
  src/components/AnonymousChat/MessageChannelItem.tsx
  src/database/hooks/useSaveAnonChatHook.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/UserSchema.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/service/chat.js
  types/database/schema/ChannelList.types.ts
Labels: need review, merge to staging, on testing

#1835 feat: ping-3568 remove message staging
  src/screens/OtherProfile/index.js
Labels: need review, merge to staging

#1818 Feat/fix emoji
  __tests__/database/schema/ChannelListSchema.test.ts
  __tests__/database/schema/UserSchema.test.ts
  __tests__/hooks/useGroupInfo.test.js
  __tests__/screens/Blocked/RenderBlock.test.js
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/assets/icon/AnonymousChatFill.tsx
  src/assets/icon/AnonymousChatOutline.tsx
  src/assets/icon/SignedChat.tsx
  src/assets/images/AnonymousProfile.png
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/MessageChannelItem.tsx
  src/components/AnonymousChat/child/ChannelAnonymousImage.tsx
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/components/Chat/InputMessageV2.tsx
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/components/Items/ProfileContact.js
  src/database/hooks/useSaveAnonChatHook.ts
  src/database/schema/ChannelListMemberSchema.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/ChatSchema.ts
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/chat/useMoveChatTypeHook.ts
  src/hooks/core/constant/index.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/core/websocket/types.d.ts
  src/hooks/screen/useAnonymousChannelListHook.ts
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/hooks/screen/useCreateChat.ts
  src/hooks/screen/useRootChannelListHook.ts
  src/hooks/screen/useSignedChannelListHook.ts
  src/navigations/HomeBottomTabs.js
  src/navigations/root-stack.js
  src/screens/ChannelListScreen/elements/Search.js
  src/screens/ChannelListScreen/index.tsx
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/Settings/index.js
  src/screens/WebsocketResearchScreen/index.tsx
  src/service/chat.js
  src/utils/constants/index.js
  src/utils/storage/index.ts
  src/utils/string/StringUtils.js
  types/component/AnonymousChat/BaseChannelItem.types.ts
  types/database/schema/ChannelList.types.ts
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
  types/hooks/screens/useChatScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
  types/service/AnonProfile.type.ts
Labels: need review, merge to main, on testing

#1832 fix: chat tab indicator broken ping 3560
  src/components/AnonymousChat/child/ChannelImage.tsx
Labels: need review, merge to staging

#1831 fix: [both chat tabs] Chat bubbles wrong size ping 3561
  src/assets/icon/IconChatCheckMark.js
  src/assets/icon/IconChatClockGrey.js
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
Labels: need review, merge to staging

#1838 fix: [both chat tabs] Chat bubbles wrong size ping 3561 main
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/assets/icon/IconChatCheckMark.js
  src/assets/icon/IconChatClockGrey.js
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
Labels: need review, merge to main

#1837 fix: chat tab indicator broken ping 3560 main
  src/components/AnonymousChat/child/ChannelImage.tsx
Labels: need review, merge to main

#1844 fix: render anon image for notification
  src/components/AnonymousChat/child/ChannelImage.tsx
Labels: need review, merge to main

#1841 feat: ping-3527 new profile screen staging
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/assets/LockIcon.js
  src/assets/PencilIcon.js
  src/assets/ShareIcon.js
  src/assets/index.js
  src/components/Divider.tsx
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
  src/screens/ProfileScreen/elements/FollowInfoRow.js
  src/screens/ProfileScreen/elements/KarmaLock.tsx
  src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
  src/screens/ProfileScreen/elements/ProfileHeader.js
  src/screens/ProfileScreen/index.js
  src/utils/theme/index.js
  yarn.lock
Labels: need review, merge to staging

#1842 feat: change caching image method
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#1783 Feat/ping 3391 blurred post main
  __tests__/screens/Blocked/RenderBlock.test.js
  __tests__/screens/FeedScreen/Content.test.js
  src/assets/icon/IconSecurityLock.js
  src/components/Footer/Footer.js
  src/screens/DiscoveryScreenV2/index.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/Header.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/elements/BlurredLayer.js
  src/screens/FeedScreen/elements/BlurredLayerToast.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#1853 feat: ping-3548-center-following staging
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
Labels: need review, merge to staging

#1846 fix: popup name missing
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
Labels: need review, merge to main

#1847 fix: missing popup name
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
Labels: need review, merge to staging

#1854 Merge/ping 3587
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
Labels: need review, merge to staging, on testing
