Repository BetterSocial/mobileapp, pull requests merged in 2024-09, with the labels that each got.

#2540 [PING-2321] fix: scrolling height improvement
  src/components/PreviewComment/index.js
  src/screens/FeedScreen/elements/AddCommentPreview.tsx
  src/screens/FeedScreen/index.js
Labels: need review, merge to main

#2537 fix: mode cover if multiple images post PING-4272
  src/screens/FeedScreen/Content.js
Labels: need review, merge to main

#2535 Fix/ping 4269
  src/screens/ContactScreen/index.js
  src/service/discovery.js
  src/utils/constants/index.js
Labels: need review, merge to main, on testing

#2541 Merge/fix/link detection
  ios/Helio.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/screens/FeedScreen/Content.js
  src/utils/string/StringUtils.js
Labels: need review, merge to staging, on testing

#2546 feat: remove location screen from the onboarding
  __tests__/context/reducers/localCommunityReducer.test.js
  src/context/reducers/localComunityReducer.js
  src/screens/InputUsername/index.js
  src/screens/SignInV2/elements/SlideShow.js
  src/screens/Topics/index.js
Labels: need review, merge to staging, on testing

#2544 feat: ping-3421 improve delay sending message
  src/hooks/screen/useChatScreenHook.ts
Labels: need review, merge to staging

#2547 [PING-4288] fix: post has image and link
  src/components/PostPageDetail/elements/Content.js
  src/screens/CreatePost/index.js
  src/screens/FeedScreen/ContentLink.js
Labels: need review, merge to staging

#2545 feat: remove location screen from the onboarding
  __tests__/context/reducers/localCommunityReducer.test.js
  src/context/reducers/localComunityReducer.js
  src/screens/InputUsername/index.js
  src/screens/SignInV2/elements/SlideShow.js
  src/screens/Topics/index.js
Labels: need review, merge to main, on testing

#2551 Fix/ping 4159 performance
  src/database/hooks/useSaveAnonChatHook.ts
  src/screens/OtherProfile/elements/BioAndChat.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2554 feat: ping-4315 link chat not implemented properly
  src/components/LinkableText.tsx
  src/service/chat.js
Labels: need review, merge to staging

#2556 feat: onesignal push notifications open and analytics
  src/hooks/core/onesignal/types.d.ts
  src/hooks/core/onesignal/useOneSignalSubscribeToCommunityHooks.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/libraries/analytics/analyticsEventTracking.ts
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/utils/constants/index.js
Labels: need review, merge to staging, on testing

#2555 feat: onesignal push notifications open and analytics
  src/hooks/core/onesignal/types.d.ts
  src/hooks/core/onesignal/useOneSignalSubscribeToCommunityHooks.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/libraries/analytics/analyticsEventTracking.ts
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/utils/constants/index.js
Labels: need review, merge to main, on testing

#2560 [PING-4319] fix: pdp image height
  src/components/PostPageDetail/elements/Content.js
Labels: need review, merge to staging

#2561 [PING-4319] fix: pdp image height
  src/components/PostPageDetail/elements/Content.js
Labels: need review, merge to main

#2563 [PING-4330] fix: dm anon not working
  src/components/Footer/Footer.js
Labels: need review, merge to main

#2562 [PING-4330] fix: dm anon not working
  src/components/Footer/Footer.js
Labels: need review, merge to staging

#2558 fix: undefined link when sharing in post detail page
  src/components/PostPageDetail/index.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2550 Fix/ping 4159 performance
  src/database/hooks/useSaveAnonChatHook.ts
  src/screens/OtherProfile/elements/BioAndChat.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2567 fix: segment and mixpanel singleton and set identity
  ios/BetterSocialStaging/Info.plist
  src/libraries/analytics/analyticsEventTracking.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2569 fix: hide checkmark
  src/components/AnonymousChat/child/ChatItemMyText.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2571 fix: delete anon chat
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/ContextMenuView/ChatContextMenuView.tsx
  src/hooks/core/chat/useMessageHook.ts
  types/component/AnonymousChat/BaseChannelItem.types.ts
  types/component/AnonymousChat/BaseChatItem.types.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2572 fix: block register function when user has already registered from th…
  src/screens/WhotoFollow/index.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2565 fix: dm from post not working
  src/components/Footer/Footer.js
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useDMMessage.ts
  src/hooks/core/chat/useSystemMessage.ts
  src/screens/TopicPageScreen/MemoizedListComponent.js
Labels: need review, merge to main, on testing

#2566 fix: segment and mixpanel singleton and set identity
  ios/BetterSocialStaging/Info.plist
  src/libraries/analytics/analyticsEventTracking.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2570 fix: delete anon chat
  src/components/AnonymousChat/BaseChatItem.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/ContextMenuView/ChatContextMenuView.tsx
  src/hooks/core/chat/useMessageHook.ts
  types/component/AnonymousChat/BaseChannelItem.types.ts
  types/component/AnonymousChat/BaseChatItem.types.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2568 fix: hide checkmark
  src/components/AnonymousChat/child/ChatItemMyText.tsx
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
Labels: need review, merge to main, waiting for visual feedback, on testing

#2576 fix: share button in own anon post
  src/components/PostPageDetail/index.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2573 feat: add channel background color depending on channelType
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/BaseChannelItemStyles.tsx
  src/components/AnonymousChat/MessageChannelItem.tsx
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/ChatList/ChannelItem.style.ts
  src/components/ChatList/CommunityChannelItem.tsx
  src/components/ChatList/GroupChatChannelItem.tsx
  src/utils/theme/index.js
  types/component/AnonymousChat/BaseChannelItem.types.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2575 fix: share button in own anon post
  src/components/PostPageDetail/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2578 fix: post text in pdp expanded
  src/components/PostPageDetail/elements/Content.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#2574 feat: add channel background color depending on channelType
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/BaseChannelItemStyles.tsx
  src/components/AnonymousChat/MessageChannelItem.tsx
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/ChatList/ChannelItem.style.ts
  src/components/ChatList/CommunityChannelItem.tsx
  src/components/ChatList/GroupChatChannelItem.tsx
  src/utils/theme/index.js
  types/component/AnonymousChat/BaseChannelItem.types.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2581 fix: add fetching channel detail and loading indicator when no channel
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#2583 fix: disable auto correct in create post screen
  src/components/CreatePostInput/index.js
Labels: need review, waiting for visual feedback, merge to staging, on testing
