Repository BetterSocial/mobileapp, pull requests merged in 2024-05, with the labels that each got.

#2304 [PING-4045] fix: no safe area cp member list
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main

#2308 feat: ping-3998 clickable link on chat screen
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/LinkableText.tsx
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/utils/theme/index.js
Labels: need review, merge to staging

#2309 Feat/segment analytics
  .babelrc
  babel.config.js
  ios/Helio.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/libraries/Configs/ENVConfig.js
  src/libraries/analytics/analyticsEventTracking.ts
  src/screens/InputUsername/index.js
  src/screens/LocalCommunity/index.js
  src/screens/SignInV2/index.js
  src/screens/Topics/index.js
  src/screens/WhotoFollow/index.js
  yarn.lock
Labels: need review, merge to staging, on testing

#2310 Feat/segment analytics
  src/libraries/analytics/analyticsEventTracking.ts
  src/screens/Topics/ListTopics.js
  src/screens/Topics/index.js
  src/screens/WhotoFollow/index.js
Labels: need review, merge to staging, on testing

#2311 [PING-3970] fix: font size cut off
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/Card/Card.js
  src/components/PostPageDetail/elements/Content.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentLink.js
  src/screens/FeedScreen/hooks/useCalculationContent.js
Labels: need review, merge to staging

#2316 feat: ping-3998 open url link on message
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/LinkableText.tsx
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
Labels: need review, merge to staging

#2307 feat: add segment sdk and add tracking on human id action
  .babelrc
  babel.config.js
  ios/Helio.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/libraries/Configs/ENVConfig.js
  src/libraries/analytics/analyticsEventTracking.ts
  src/screens/InputUsername/index.js
  src/screens/LocalCommunity/index.js
  src/screens/SignInV2/index.js
  src/screens/Topics/ListTopics.js
  src/screens/Topics/index.js
  src/screens/WhotoFollow/index.js
  yarn.lock
Labels: need review, merge to main, on testing

#2312 [PING-3970] fix: font size cut off
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/Card/Card.js
  src/components/PostPageDetail/elements/Content.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentLink.js
  src/screens/FeedScreen/hooks/useCalculationContent.js
Labels: need review, merge to main

#2323 feat: ping-3988 clickable link messge
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/LinkableText.tsx
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/utils/theme/index.js
Labels: need review, merge to staging

#2326 feat: ping-4096 fix app crash on pn
  src/hooks/core/push-notification/usePushNotificationHook.ts
Labels: need review, merge to staging

#2315 feat: ping-3988 clickable link messge
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemTargetText.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/AnonymousChat/child/ChatItemTargetText.tsx
  src/components/LinkableText.tsx
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/utils/theme/index.js
Labels: merge to main

#2317 Fix/ping 3295 follow button
  __tests__/hooks/useFollowUser.test.js
  src/components/AnonymousChat/BaseChannelItem.tsx
  src/components/AnonymousChat/MessageChannelItem.tsx
  src/hooks/core/users/useFollowUserV2Hook.tsx
  src/screens/ChannelListScreen/hooks/useFollowUser.ts
  src/screens/ChannelListScreen/index.tsx
  src/service/repo/signedMessageRepo.ts
  src/service/users.js
  types/component/AnonymousChat/BaseChannelItem.types.ts
  types/component/AnonymousChat/MessageChannelItem.types.ts
Labels: need review, merge to main, on testing

#2338 feat: ping-4044 retry send pending message
  src/database/schema/ChatSchema.ts
  src/hooks/screen/useChatScreenHook.ts
  src/navigations/root-stack.js
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/service/chat.js
  types/hooks/screens/useChatScreenHook.types.ts
Labels: need review, merge to staging

#2343 feat: ping-4068 chat screen not updating
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/hooks/screen/useChatScreenHook.ts
  types/hooks/screens/useChatScreenHook.types.ts
Labels: need review, merge to staging

#2345 feat: add link detection on bio
  ios/Helio.xcodeproj/project.pbxproj
  src/components/LinkableText.tsx
  src/screens/OtherProfile/elements/BioAndChat.js
  src/screens/ProfileScreen/elements/TextWithEmoji.tsx
  src/utils/string/StringUtils.js
Labels: need review, merge to staging, on testing

#2344 feat: add link detection on bio
  ios/Helio.xcodeproj/project.pbxproj
  src/components/LinkableText.tsx
  src/screens/OtherProfile/elements/BioAndChat.js
  src/screens/ProfileScreen/elements/TextWithEmoji.tsx
  src/utils/string/StringUtils.js
Labels: need review, merge to main, on testing

#2346 fix: ping-4044 sending message and media
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
Labels: need review, merge to staging

#2336 Create community v1 PING-4019
  __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap
  src/assets/icons/Ic_user_group.js
  src/assets/icons/ic_topic.js
  src/components/Input/Input.js
  src/hooks/screen/useCreatePostHook.js
  src/navigations/root-stack.js
  src/screens/CreateCommunity/index.js
  src/screens/CreatePost/index.js
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
  src/screens/FeedScreen/elements/Search.js
  src/screens/index.js
  src/service/topics.ts
  src/utils/string/StringConstant/index.js
Labels: need review, merge to staging

#2337 feat: ping-4044 retry send pending message
  src/database/schema/ChatSchema.ts
  src/hooks/screen/useChatScreenHook.ts
  src/navigations/root-stack.js
  src/screens/ChatScreen/AnonymousChatScreen.tsx
  src/screens/ChatScreen/SignedChatScreen.tsx
  src/service/chat.js
  types/hooks/screens/useChatScreenHook.types.ts
Labels: need review, merge to main

#2363 Fix/ping 3870 force search
  ios/Helio.xcodeproj/project.pbxproj
  src/screens/DiscoveryScreenV2/elements/Search.js
Labels: need review, merge to staging, on testing

#2360 fix: loading and retry failed create post PING-4043
  src/screens/CreatePost/index.js
Labels: need review, merge to staging

#2364 feat: grouping pending message
  src/database/schema/ChatSchema.ts
Labels: need review, merge to staging
