Repository BetterSocial/mobileapp, pull requests merged in 2024-08, with the labels that each got.

#2487 fix: push notification case not opening correct chat screen
  src/atom/currentChatScreenAtom.ts
  src/hooks/core/push-notification/usePushNotificationHook.ts
  src/hooks/screen/useChatScreenHook.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#2496 fix: other profile follow button when opening from deeplink
  src/screens/DiscoveryScreenV2/hooks/useDiscovery.js
  src/screens/OtherProfile/index.js
Labels: need review, merge to staging, on testing

#2497 fix: crash PING-4216
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
Labels: need review, merge to staging

#2506 [PING-4033] fix: comment preview cut off
  src/components/PreviewComment/index.js
Labels: need review, merge to staging

#2485 [PING-3772] fix: block in comment
  src/components/BlockComponent/index.js
  src/components/Comments/Comment.js
  src/components/Comments/ContainerComment.js
  src/components/PostPageDetail/index.js
  src/service/utils/blockUtils.js
Labels: need review, merge to staging

#2522 fix: upvotes on Post Display Page broken PING-4232
  src/screens/ProfileScreen/elements/RenderItem.js
Labels: need review, merge to staging

#2519 fix: domain follow and count issue PING-4228 and PING-4234
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DomainScreen/index.js
Labels: need review, merge to staging

#2525 Fix/ping 4254 change onboarding0image
  src/assets/background/fg_onboarding_full_1.png
  src/assets/background/fg_onboarding_full_2.png
  src/assets/background/fg_onboarding_full_3.png
  src/assets/background/fg_onboarding_full_4.png
Labels: merge to main, on testing

#2512 fix: domain follow and count issue PING-4228 and PING-4234
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
  src/screens/DomainScreen/index.js
Labels: need review, merge to main

#2509 fix: join topic button PING-4224
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
Labels: need review, merge to main

#2513 fix: slow loading topic PING-4158
  src/hooks/useInitialStartup.js
Labels: need review, merge to main

#2514 fix: cannot scroll to the end of communities list PING-4252
  src/screens/DiscoveryScreenV2/fragment/TopicFragment.js
Labels: need review, merge to main

#2532 fix: feed keep loading PING-4262
  src/navigations/HomeBottomTabs.js
  src/screens/FeedScreen/hooks/useCoreFeed.js
Labels: need review, merge to staging

#2536 Fix/ping 4269
  ios/BetterSocial/AppDelegate.m
  ios/Helio.xcodeproj/project.pbxproj
  src/libraries/analytics/analyticsEventTracking.ts
  src/screens/ContactScreen/index.js
  src/screens/SignInV2/elements/SlideShow.js
  src/screens/SignInV2/elements/SlideShowItem.js
  src/service/discovery.js
  src/utils/constants/index.js
Labels: need review, merge to staging, on testing

#2533 Fix/ping 4222 follow button deeplink
  src/configs/FirebaseConfig.js
  src/screens/DiscoveryScreenV2/hooks/useDiscovery.js
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/screens/OtherProfile/index.js
Labels: need review, merge to staging, on testing

#2495 fix: other profile follow button when opening from deeplink
  src/configs/FirebaseConfig.js
  src/screens/DiscoveryScreenV2/hooks/useDiscovery.js
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/screens/OtherProfile/index.js
Labels: need review, merge to main, on testing

#2539 [PING-2321] fix: scrolling height improvement
  src/components/PreviewComment/index.js
  src/screens/FeedScreen/elements/AddCommentPreview.tsx
  src/screens/FeedScreen/index.js
Labels: need review, merge to staging
