Repository BetterSocial/mobileapp, pull requests merged in 2024-02, with the labels that each got.

#1856 feat: add feed preview comment
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/Comments/WriteComment.js
  src/components/PostPageDetail/index.js
  src/components/ToggleSwitch/index.tsx
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentLink.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/index.js
  src/screens/OtherProfile/index.js
  src/screens/OtherProfilePostDetail/index.js
  src/screens/PostPageDetail/index.js
  src/screens/ProfileScreen/elements/RenderItem.js
  src/screens/ProfileScreen/index.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/index.js
Labels: merge to main

#1857 fix: feed on press handler
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/index.js
  src/screens/ProfileScreen/index.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main

#1858 fix: revert topic page screen
  src/screens/TopicPageScreen/index.js
Labels: need review, merge to main

#1859 fix: my profile crash staging
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
Labels: need review, merge to staging

#1855 Fix/ping 3587 fallback user picture
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/DiscoveryScreenV2/fragment/DomainFragment.js
Labels: need review, merge to main, on testing

#1875 feat: ping-3527 new profile screen
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/assets/LockIcon.js
  src/assets/PencilIcon.js
  src/assets/ShareIcon.js
  src/assets/index.js
  src/components/Divider.tsx
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
  src/screens/ProfileScreen/elements/FollowInfoRow.js
  src/screens/ProfileScreen/elements/KarmaLock.tsx
  src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
  src/screens/ProfileScreen/elements/ProfileHeader.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
  src/screens/ProfileScreen/index.js
  src/utils/theme/index.js
  yarn.lock
Labels: need review, merge to staging

#1874 feat: ping-3568 remove message
  src/screens/OtherProfile/index.js
Labels: need review, merge to staging

#1876 feat: ping-3548-center-following
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
Labels: need review, merge to staging

#1877 feat: ping-3526 add karma on other component
  __tests__/components/AnonymousAvatar/__snapshots__/index.test.js.snap
  src/components/AnonymousAvatar/index.js
  src/components/Comments/Comment.js
  src/components/Comments/ReplyCommentItem.js
  src/components/PreviewComment/index.js
  src/screens/CreatePost/elements/UserProfile.js
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/FeedScreen/Header.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#1870 style: flexible image height on link content
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  src/components/Card/Card.js
  src/components/Comments/WriteComment.js
Labels: need review, merge to staging, on testing

#1852 feat: ping-3548-center-following
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
Labels: need review, merge to main

#1850 feat: ping-3568 remove message
  src/screens/OtherProfile/index.js
Labels: need review, merge to main

#1867 fix: mention user with no user id
  src/components/Comments/WriteComment.js
  src/screens/CreatePost/index.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#1883 fix: cant interact profile pict
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#1889 Merge/ping 3621
  __tests__/components/AnonymousAvatar/__snapshots__/index.test.js.snap
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ContactScreen/index.js
  types/database/schema/ChannelList.types.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#1884 Feat/ping 3263 start new anon chat staging
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  src/assets/icons/Ic_Checklist.js
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/components/Header/HeaderContact.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ContactScreen/elements/ItemUser.js
  src/screens/ContactScreen/index.js
  src/utils/string/StringConstant/index.js
  src/utils/theme/index.js
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
Labels: need review, merge to staging, on testing

#1892 fix: feedback my profile
  src/assets/icons/Ic_question_mark.js
  src/screens/ProfileScreen/elements/AnonymousTab.js
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
  src/screens/ProfileScreen/elements/KarmaLock.tsx
  src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
  src/screens/ProfileScreen/index.js
Labels: need review, merge to staging

#1890 fix: remove default topic image when saving to DB
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/components/ChatList/elements/ChannelImage.style.ts
  src/components/ChatList/elements/ChannelImage.tsx
  src/utils/string/StringUtils.js
Labels: need review, waiting for visual feedback, merge to staging, on testing

#1891 fix: remove default topic image when saving to DB
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/components/ChatList/elements/ChannelImage.style.ts
  src/components/ChatList/elements/ChannelImage.tsx
  src/utils/string/StringUtils.js
Labels: need review, merge to main, on testing

#1888 fix: test case 13 creating group chat
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useChatScreenHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ContactScreen/index.js
  types/database/schema/ChannelList.types.ts
Labels: need review, merge to main, on testing

#1887 fix: onboarding screens 4 text style
  src/screens/WhotoFollow/index.js
Labels: need review, merge to main, on testing

#1851 feat: ping-3527 new profile screen
  ios/BetterSocial.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/assets/LockIcon.js
  src/assets/PencilIcon.js
  src/assets/ShareIcon.js
  src/assets/icons/Ic_question_mark.js
  src/assets/index.js
  src/components/Divider.tsx
  src/screens/ProfileScreen/elements/AnonymousTab.js
  src/screens/ProfileScreen/elements/BioAndDMSetting.tsx
  src/screens/ProfileScreen/elements/FollowInfoRow.js
  src/screens/ProfileScreen/elements/KarmaLock.tsx
  src/screens/ProfileScreen/elements/LinkAndSocialMedia.tsx
  src/screens/ProfileScreen/elements/ProfileHeader.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
  src/screens/ProfileScreen/index.js
  src/utils/theme/index.js
  yarn.lock
Labels: need review, merge to main

#1849 feat: ping-3526 add karma on other component
  __tests__/components/AnonymousAvatar/__snapshots__/index.test.js.snap
  src/components/AnonymousAvatar/index.js
  src/components/Comments/Comment.js
  src/components/Comments/ReplyCommentItem.js
  src/components/PreviewComment/index.js
  src/screens/CreatePost/elements/UserProfile.js
  src/screens/DiscoveryScreenV2/elements/DiscoveryItemList.js
  src/screens/FeedScreen/Header.js
  src/screens/OtherProfile/index.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to main

#1900 fix: ping-3480 Going back to discovery doesnt save position/search
  src/navigations/root-stack.js
  src/screens/DiscoveryScreenV2/index.js
Labels: need review, merge to staging

#1901 fix: followings screen layout
  src/navigations/root-stack.js
Labels: need review, merge to staging

#1898 fix: add white background color on home bottom tabs
  src/navigations/HomeBottomTabs.js
Labels: need review, merge to staging, on testing

#1894 fix: fix wrong disable button color
  src/components/Button/Button.js
  src/utils/theme/index.js
Labels: need review, merge to staging

#1897 Feat/ping 3627 fetch channel detail
  src/components/AnonymousChat/ChatDetailHeader.tsx
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/hooks/screen/useChatInfoHook.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  src/service/repo/types.d.ts
  types/hooks/screens/useAnonymousChatInfoScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
Labels: need review, merge to staging, on testing

#1903 fix: ping-3646 karma anon missing
  src/components/PreviewComment/index.js
  src/screens/FeedScreen/Header.js
Labels: need review, merge to staging

#1895 PING 3619 fix wrong disable button color
  src/components/Button/Button.js
  src/utils/theme/index.js
Labels: merge to main

#1893 fix: add white background color on home bottom tabs
  src/navigations/HomeBottomTabs.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#1896 Feat/ping 3627 fetch channel detail
  src/components/AnonymousChat/ChatDetailHeader.tsx
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/core/websocket/useSimpleWebsocketHooks.tsx
  src/hooks/screen/useChatInfoHook.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/service/repo/anonymousMessageRepo.ts
  src/service/repo/signedMessageRepo.ts
  src/service/repo/types.d.ts
  types/hooks/screens/useAnonymousChatInfoScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#1905 fix: blurred layer and preview comment on feed
  __tests__/components/Comments/WriteComment.test.js
  __tests__/screens/FeedScreen/__snapshots__/ContentLink.test.js.snap
  __tests__/screens/FeedScreen/__snapshots__/ContentPoll.test.js.snap
  src/components/Card/Card.js
  src/components/Comments/WriteComment.js
  src/components/TopicsChip/TopicsChip.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentLink.js
  src/screens/FeedScreen/ContentPoll.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/elements/BlurredLayer.js
Labels: need review, merge to main

#1914 fix: ping-3646 karma anon missing staging
  src/screens/FeedScreen/Header.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to staging

#1917 chore: merge PING-3622
  App.js
  __tests__/components/AnonymousAvatar/__snapshots__/index.test.js.snap
  __tests__/components/Comments/WriteComment.test.js
  __tests__/components/PreviewComment/PreviewComment.test.js
  src/components/Comments/WriteComment.js
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/service/chat.js
  types/core/AnonUserInfoTs.types.ts
  types/repo/AnonymousMessageRepo/MessageAnonymouslyData.ts
Labels: need review, waiting for visual feedback, merge to staging, on testing

#1920 [PING-3631][PING-3633] fix: onboarding and create post incognito text
  src/assets/onboarding/OnboardingText1.js
  src/assets/onboarding/OnboardingText2.js
  src/assets/onboarding/OnboardingText3.js
  src/assets/onboarding/OnboardingText4.js
  src/screens/CreatePost/index.js
  src/screens/SignInV2/elements/BottomOverlay/index.js
  src/screens/SignInV2/elements/SlideShow.js
  src/screens/SignInV2/elements/SlideShowItem.js
Labels: need review, merge to staging

#1922 Merge/ping 3578
  package.json
  yarn.lock
Labels: need review, merge to staging

#1921 chore: changelibrary url to bettersocial
  package.json
  yarn.lock
Labels: need review, merge to staging

#1902 fix: ping-3646 karma anon missing
  src/components/PreviewComment/index.js
  src/screens/FeedScreen/Header.js
  src/screens/ProfileScreen/elements/ProfilePicture.js
Labels: need review, merge to main

#1918 fix: topic feed comment
  src/components/Comments/ContainerComment.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/elements/AddCommentPreview.tsx
  src/screens/TopicPageScreen/MemoizedListComponent.js
Labels: need review, merge to staging

#1913 fix: topic feeds comment
  src/components/Comments/ContainerComment.js
  src/screens/FeedScreen/RenderList.js
  src/screens/FeedScreen/elements/AddCommentPreview.tsx
  src/screens/TopicPageScreen/MemoizedListComponent.js
Labels: need review, merge to main

#1935 Merge/other profile chat
  __tests__/database/schema/ChannelListSchema.test.ts
  __tests__/database/schema/UserSchema.test.ts
  src/database/hooks/useSaveAnonChatHook.ts
  src/database/schema/ChannelListMemberSchema.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/DiscoveryScreenV2/index.js
  src/screens/OtherProfile/elements/BioAndChat.js
  src/utils/string/StringUtils.js
Labels: need review, merge to staging, on testing

#1938 [PING-3691] fix: preview comment crash staging
  src/components/Comments/WriteComment.js
  src/screens/FeedScreen/RenderList.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
Labels: need review, merge to staging

#1932 [PING-3691] fix: preview comment height
  src/components/Comments/WriteComment.js
  src/screens/FeedScreen/RenderList.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
Labels: need review, merge to main

#1899 fix: ping-3480 Going back to discovery doesnt save position/search
  src/navigations/root-stack.js
  src/screens/DiscoveryScreenV2/elements/Search.js
  src/screens/DiscoveryScreenV2/index.js
Labels: need review, merge to main

#1939 feat: 3504 improve speed transition
  src/components/PostPageDetail/elements/Content.js
  src/components/PostPageDetail/index.js
  src/navigations/root-stack.js
  src/screens/FeedScreen/hooks/useCoreFeed.js
  src/screens/FeedScreen/index.js
  src/screens/PostPageDetail/index.js
Labels: merge to main

#1944 fix: ping-3674 not align preview comment
  __tests__/components/PreviewComment/PreviewComment.test.js
  src/components/PreviewComment/index.js
Labels: need review, merge to staging

#1940 fix: ping-3674 not align preview comment
  __tests__/components/PreviewComment/PreviewComment.test.js
  src/components/PreviewComment/index.js
Labels: need review, merge to main

#1924 chore: rebase
  src/navigations/root-stack.js
  src/screens/OtherProfile/hooks/useOtherProfileScreenHooks.tsx
  src/screens/OtherProfile/index.js
  src/screens/TopicPageScreen/index.js
  src/utils/storage/index.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#1929 Fix/other profile chat
  __tests__/database/schema/ChannelListSchema.test.ts
  __tests__/database/schema/UserSchema.test.ts
  src/database/hooks/useSaveAnonChatHook.ts
  src/database/schema/ChannelListMemberSchema.ts
  src/database/schema/ChannelListSchema.ts
  src/database/schema/UserSchema.ts
  src/hooks/core/chat/useFetchChannelHook.ts
  src/hooks/core/useCoreChatSystemHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/DiscoveryScreenV2/index.js
  src/screens/OtherProfile/elements/BioAndChat.js
  src/utils/string/StringUtils.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#1947 chore: add new test account and custom id input
  __tests__/components/DummyLogin/__snapshots__/DummyLogin.test.js.snap
  src/components/DevDummyLogin/index.js
Labels: need review, merge to main, on testing

#1950 [PING-3692][PING-3645] fix: render feed feedback
  __tests__/components/Comments/WriteComment.test.js
  src/components/Comments/WriteComment.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentPoll.js
  src/screens/FeedScreen/RenderList.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/elements/NavHeader.js
Labels: need review, merge to staging

#1956 fix: create new post anon text
  src/components/WarningAnimateMessage/index.js
  src/screens/CreatePost/index.js
Labels: need review, merge to staging

#1952 fix: change generate anonymous username token to anonymous
  src/service/anonymousProfile.ts
  src/service/repo/anonUserInfoRepo.js
Labels: need review, merge to staging, on testing

#1959 Fix/ping 3701 post notification
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useFetchPostNotificationHook.ts
  types/repo/AnonymousMessageRepo/AnonymousPostNotificationData.ts
  types/repo/SignedMessageRepo/SignedPostNotificationData.ts
Labels: need review, merge to staging, on testing

#1962 feat: ping-3693 presignup onboarding staging
  src/assets/background/bg_onboarding_5_top.png
  src/assets/background/bg_onboarding_top.png
  src/assets/icon/IconBetterOnboarding.js
  src/assets/images/button-sign.png
  src/screens/SignInV2/elements/BottomOverlay/index.js
  src/screens/SignInV2/elements/SlideShowItem.js
Labels: need review, merge to staging

#1916 fix: message-anonymously
  src/database/schema/ChannelListSchema.ts
  src/hooks/screen/useChatInfoHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/service/chat.js
  types/core/AnonUserInfoTs.types.ts
  types/repo/AnonymousMessageRepo/MessageAnonymouslyData.ts
Labels: need review, merge to main, waiting for visual feedback, on testing

#1951 fix: change generate anonymous username token to anonymous
  src/service/anonymousProfile.ts
  src/service/repo/anonUserInfoRepo.js
Labels: need review, merge to main, waiting for visual feedback, on testing

#1969 feat: ping-3615 Random mentions of the brand on the app staging
  README.md
  __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap
  src/components/Blocking/BlockDomain.js
  src/components/Blocking/BlockPostAnonymous.js
  src/components/Blocking/BlockProfile.js
  src/components/Blocking/BlockUser.js
  src/components/Chat/InputMessageV2.tsx
  src/screens/CreatePost/index.js
  src/screens/ProfileScreen/index.js
  src/screens/WhotoFollow/index.js
  src/screens/WhotoFollow/index_old.js
  src/service/utils/blockUtils.js
  src/utils/string/StringConstant/index.js
Labels: need review, merge to staging

#1949 [PING-3692][PING-3645] fix: render feed feedback
  __tests__/components/Comments/WriteComment.test.js
  src/components/Comments/WriteComment.js
  src/screens/FeedScreen/Content.js
  src/screens/FeedScreen/ContentPoll.js
  src/screens/FeedScreen/RenderList.js
  src/screens/TopicPageScreen/MemoizedListComponent.js
  src/screens/TopicPageScreen/elements/NavHeader.js
Labels: need review, merge to main

#1967 fix: ping-3693 design layout preonboarding staging
  src/screens/SignInV2/elements/BottomOverlay/index.js
Labels: need review, merge to staging

#1971 feat: ping-3694 change welcome text staging
  src/screens/WhotoFollow/index.js
  src/screens/WhotoFollow/index_old.js
Labels: need review, merge to staging

#1973 feat: ping-3713 change link on setting screen staging
  src/screens/WebView/HelpCenter.js
  src/screens/WebView/PrivacyPolicies.js
Labels: need review, merge to staging

#1965 Merge/ping 3636
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/AnonymousUsername/index.js
  src/components/CommentUsername/CommentUsername.js
  src/components/Comments/hooks/useWriteComment.js
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChannelListScreen/elements/components/PostNotificationPreview.js
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/GroupInfo/index.js
  src/screens/GroupSetting/index.js
  src/utils/string/StringUtils.js
Labels: need review, merge to staging, on testing

#1976 Fix/ping 3701 rebase
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelTitle.test.tsx.snap
  __tests__/hooks/useChannel.test.js
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/AnonymousChat/child/ChannelPostNotificationMessage.tsx
  src/components/AnonymousChat/child/ChannelTitle.tsx
  src/hooks/screen/useChannelHook.ts
  types/database/schema/PostNotificationChannelList.types.ts
Labels: need review, merge to staging, on testing

#1977 feat: ping 3263 start new anon chat staging
  __tests__/screens/ChannelListScreenV2/__snapshots__/ChannelListScreenV2.test.js.snap
  __tests__/screens/GroupSetting/__snapshots__/GroupSetting.test.js.snap
  src/assets/icons/Ic_Checklist.js
  src/components/ChatList/ChannelListHeaderItem.tsx
  src/components/Header/HeaderContact.js
  src/components/Items/ProfileContact.js
  src/hooks/core/chat/useChatUtilsHook.ts
  src/hooks/screen/useCreateChat.ts
  src/screens/ChannelListScreenV2/AnonymousChannelListScreen/index.tsx
  src/screens/ContactScreen/elements/ItemUser.js
  src/screens/ContactScreen/elements/RenderItem.js
  src/screens/ContactScreen/index.js
  src/utils/string/StringConstant/index.js
  src/utils/theme/index.js
  types/hooks/screens/useAnonymousChannelListScreenHook.types.ts
  types/hooks/screens/useChatUtilsHook.types.ts
  types/hooks/screens/useSignedChannelListScreenHook.types.ts
Labels: need review, merge to staging

#1964 Fix/ping 3636 pseudonym
  ios/BetterSocial/Images.xcassets/AppIcon.appiconset/Contents.json
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/AnonymousUsername/index.js
  src/components/CommentUsername/CommentUsername.js
  src/components/Comments/hooks/useWriteComment.js
  src/hooks/screen/useChatScreenHook.ts
  src/screens/ChannelListScreen/elements/components/PostNotificationPreview.js
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  src/screens/GroupInfo/hooks/useGroupInfo.js
  src/screens/GroupInfo/index.js
  src/screens/GroupSetting/index.js
  src/utils/string/StringUtils.js
Labels: need review, merge to main, on testing

#1981 fix: ping 3711 search gif broken
  src/components/Chat/BottomSheetGif.js
  src/service/gif.js
  src/utils/permission/index.js
Labels: need review, merge to staging

#1961 feat: ping-3693 presignup onboarding
  src/assets/background/bg_onboarding_5_top.png
  src/assets/background/bg_onboarding_top.png
  src/assets/icon/IconBetterOnboarding.js
  src/assets/images/button-sign.png
  src/screens/SignInV2/elements/BottomOverlay/index.js
  src/screens/SignInV2/elements/SlideShowItem.js
Labels: need review, merge to main

#1970 feat: ping-3694 change welcome text
  src/screens/WhotoFollow/index.js
  src/screens/WhotoFollow/index_old.js
Labels: need review, merge to main

#1972 feat: ping-3713 change link on setting screen
  src/screens/WebView/HelpCenter.js
  src/screens/WebView/PrivacyPolicies.js
Labels: need review, merge to main

#1968 feat: ping-3615 Random mentions of the brand on the app
  README.md
  __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap
  src/components/Blocking/BlockDomain.js
  src/components/Blocking/BlockPostAnonymous.js
  src/components/Blocking/BlockProfile.js
  src/components/Blocking/BlockUser.js
  src/components/Chat/InputMessageV2.tsx
  src/screens/CreatePost/index.js
  src/screens/ProfileScreen/index.js
  src/service/utils/blockUtils.js
  src/utils/string/StringConstant/index.js
Labels: need review, merge to main

#1989 fix: remove setting image when following and creating post
  src/hooks/core/useCoreChatSystemHook.ts
  src/libraries/reactotron/reactotronInstance.js
  src/screens/CreatePost/index.js
  src/utils/constants/index.js
  src/utils/getstream/useChatClientHook.js
  src/utils/string/StringUtils.js
  types/repo/ChannelData.ts
Labels: need review, merge to staging, on testing

#1991 Feat/splash screen
  android/app/src/main/res/drawable-hdpi/helio.png
  android/app/src/main/res/drawable-ldpi/helio.png
  android/app/src/main/res/drawable-xhdpi/helio.png
  android/app/src/main/res/drawable-xxhdpi/helio.png
  android/app/src/main/res/drawable-xxxhdpi/helio.png
  android/app/src/main/res/drawable/helio.png
  android/app/src/main/res/drawable/splash_screen.png
  android/app/src/main/res/drawable/splash_theme.xml
  android/app/src/main/res/drawable/splash_theme_background.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/Contents.json
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_1x.png
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_2x.png
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_3x.png
  ios/BetterSocial/LaunchScreen.storyboard
Labels: need review, merge to staging, on testing

#1958 Fix/ping 3701 post notification
  __tests__/components/AnonymousChat/child/__snapshots__/ChannelTitle.test.tsx.snap
  __tests__/hooks/useChannel.test.js
  src/components/AnonymousChat/PostNotificationChannelItem.tsx
  src/components/AnonymousChat/child/ChannelImage.tsx
  src/components/AnonymousChat/child/ChannelPostNotificationMessage.tsx
  src/components/AnonymousChat/child/ChannelTitle.tsx
  src/database/schema/ChannelListSchema.ts
  src/hooks/core/chat/useFetchPostNotificationHook.ts
  src/hooks/screen/useChannelHook.ts
  src/screens/ChatInfoScreen/ChatInfoScreen.tsx
  types/database/schema/PostNotificationChannelList.types.ts
  types/repo/AnonymousMessageRepo/AnonymousPostNotificationData.ts
  types/repo/SignedMessageRepo/SignedPostNotificationData.ts
Labels: need review, merge to main, on testing

#1986 fix: remove setting image when following and creating post
  src/hooks/core/useCoreChatSystemHook.ts
  src/libraries/reactotron/reactotronInstance.js
  src/screens/CreatePost/index.js
  src/utils/constants/index.js
  src/utils/getstream/useChatClientHook.js
  src/utils/string/StringUtils.js
  types/repo/ChannelData.ts
Labels: need review, merge to main, on testing

#1992 Feat/splash screen
  android/app/src/main/res/drawable-hdpi/helio.png
  android/app/src/main/res/drawable-ldpi/helio.png
  android/app/src/main/res/drawable-xhdpi/helio.png
  android/app/src/main/res/drawable-xxhdpi/helio.png
  android/app/src/main/res/drawable-xxxhdpi/helio.png
  android/app/src/main/res/drawable/helio.png
  android/app/src/main/res/drawable/splash_screen.png
  android/app/src/main/res/drawable/splash_theme.xml
  android/app/src/main/res/drawable/splash_theme_background.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/Contents.json
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_1x.png
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_2x.png
  ios/BetterSocial/Images.xcassets/HelioSplashScreen.imageset/helio_3x.png
  ios/BetterSocial/LaunchScreen.storyboard
Labels: need review, merge to main, on testing

#1994 [PING-3628] fix: toggle anon
  src/components/Chat/InputMessageV2.tsx
  src/hooks/useToggleColors.js
  src/screens/CreatePost/elements/UserProfile.js
  src/screens/OtherProfile/elements/BioAndChat.js
Labels: need review, merge to staging

#1996 Fix/ping 3711 search gif staging
  __tests__/components/AnonymousChat/child/__snapshots__/ChatItemMyTextV2.test.tsx.snap
  src/components/AnonymousChat/child/ChatItemMyTextV2.tsx
  src/components/Chat/BottomSheetGif.js
  src/service/gif.js
  src/utils/permission/index.js
Labels: need review, merge to staging

#1993 [PING-3628] fix: toggle anon
  src/components/Chat/InputMessageV2.tsx
  src/hooks/useToggleColors.js
  src/screens/CreatePost/elements/UserProfile.js
  src/screens/OtherProfile/elements/BioAndChat.js
Labels: need review, merge to main

#1995 [PING-2508] feat: community anon follow
  src/assets/dp-topics-anon.png
  src/assets/dp-topics-signed.png
  src/assets/icon/IconCheckCircleOutline.tsx
  src/assets/icon/IconClose.tsx
  src/assets/icon/IconIncognito.tsx
  src/assets/icon/PostToCommunity.js
  src/components/BottomSheet/BottomSheetV2.tsx
  src/components/BottomSheet/index.js
  src/components/Button/ButtonAddPostTopic.js
  src/screens/CreatePost/elements/UserProfile.js
  src/screens/CreatePost/index.js
  src/screens/TopicMemberScreen/elements/TopicMemberHeadlineList.tsx
  src/screens/TopicMemberScreen/index.js
  src/screens/TopicPageScreen/elements/BottomSheetFollow.tsx
  src/screens/TopicPageScreen/elements/ButtonFollowing.js
  src/screens/TopicPageScreen/elements/NavHeader.js
  src/screens/TopicPageScreen/elements/TopicDomainHeader.js
  src/screens/TopicPageScreen/elements/UserItem.tsx
  src/screens/TopicPageScreen/index.js
  src/service/topics.js
  src/utils/getstream/useChatClientHook.js
Labels: need review, merge to staging
